/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="next/navigation-types/compat/navigation" />

// NOTE: This file should not be edited
// See https://nextjs.org/docs/app/building-your-application/configuring/typescript for more information.

// Environment Variables Type Definitions
declare namespace NodeJS {
  interface ProcessEnv {
    // Next.js
    NODE_ENV: 'development' | 'production' | 'test'
    NEXT_PUBLIC_APP_URL: string
    NEXT_PUBLIC_VERCEL_URL?: string
    
    // Supabase
    NEXT_PUBLIC_SUPABASE_URL: string
    NEXT_PUBLIC_SUPABASE_ANON_KEY: string
    SUPABASE_SERVICE_ROLE_KEY: string
    
    // Groq AI
    GROQ_API_KEY: string
    
    // Payment Gateway
    RAZORPAY_KEY_ID: string
    RAZORPAY_KEY_SECRET: string
    
    // Analytics
    NEXT_PUBLIC_GA_ID: string
    NEXT_PUBLIC_SENTRY_DSN: string
    
    // Email Service
    RESEND_API_KEY: string
    SMTP_HOST: string
    SMTP_PORT: string
    SMTP_USER: string
    SMTP_PASS: string
    
    // Security
    JWT_SECRET: string
    ENCRYPTION_KEY: string
    
    // External APIs
    GOOGLE_PLACES_API_KEY: string
    LINKEDIN_API_KEY: string
  }
}

// Global Type Augmentations
declare global {
  // Add custom window properties
  interface Window {
    gtag: (...args: any[]) => void
    dataLayer: any[]
    Razorpay: any
    // PWA install prompt
    beforeinstallprompt: any
  }
  
  // Service Worker Registration
  interface Navigator {
    serviceWorker: ServiceWorkerContainer
  }
  
  // Web Share API
  interface Navigator {
    share?: (data?: ShareData) => Promise<void>
  }
  
  // Speech Synthesis
  interface Window {
    SpeechSynthesisUtterance: typeof SpeechSynthesisUtterance
    speechSynthesis: SpeechSynthesis
  }
  
  interface ShareData {
    title?: string
    text?: string
    url?: string
    files?: File[]
  }
}

// Module Declarations
declare module 'groq-sdk' {
  export default class Groq {
    constructor(config: { apiKey: string })
    chat: {
      completions: {
        create: (params: any) => Promise<any>
      }
    }
  }
}

declare module 'lucide-react' {
  import { FC, SVGProps } from 'react'
  export const Search: FC<SVGProps<SVGSVGElement>>
  export const Bell: FC<SVGProps<SVGSVGElement>>
  export const User: FC<SVGProps<SVGSVGElement>>
  export const Home: FC<SVGProps<SVGSVGElement>>
  export const Settings: FC<SVGProps<SVGSVGElement>>
  export const LogOut: FC<SVGProps<SVGSVGElement>>
  export const ChevronDown: FC<SVGProps<SVGSVGElement>>
  export const Menu: FC<SVGProps<SVGSVGElement>>
  export const X: FC<SVGProps<SVGSVGElement>>
  export const AlertCircle: FC<SVGProps<SVGSVGElement>>
  export const CheckCircle: FC<SVGProps<SVGSVGElement>>
  export const Info: FC<SVGProps<SVGSVGElement>>
  export const Star: FC<SVGProps<SVGSVGElement>>
  export const Heart: FC<SVGProps<SVGSVGElement>>
  export const Share2: FC<SVGProps<SVGSVGElement>>
  export const Download: FC<SVGProps<SVGSVGElement>>
  export const Upload: FC<SVGProps<SVGSVGElement>>
  export const Eye: FC<SVGProps<SVGSVGElement>>
  export const EyeOff: FC<SVGProps<SVGSVGElement>>
  export const Lock: FC<SVGProps<SVGSVGElement>>
  export const Unlock: FC<SVGProps<SVGSVGElement>>
  export const Mail: FC<SVGProps<SVGSVGElement>>
  export const Phone: FC<SVGProps<SVGSVGElement>>
  export const MapPin: FC<SVGProps<SVGSVGElement>>
  export const Globe: FC<SVGProps<SVGSVGElement>>
  export const Calendar: FC<SVGProps<SVGSVGElement>>
  export const Clock: FC<SVGProps<SVGSVGElement>>
  export const CreditCard: FC<SVGProps<SVGSVGElement>>
  export const DollarSign: FC<SVGProps<SVGSVGElement>>
  export const TrendingUp: FC<SVGProps<SVGSVGElement>>
  export const TrendingDown: FC<SVGProps<SVGSVGElement>>
  export const BarChart3: FC<SVGProps<SVGSVGElement>>
  export const PieChart: FC<SVGProps<SVGSVGElement>>
  export const LineChart: FC<SVGProps<SVGSVGElement>>
  export const Filter: FC<SVGProps<SVGSVGElement>>
  export const SortAsc: FC<SVGProps<SVGSVGElement>>
  export const SortDesc: FC<SVGProps<SVGSVGElement>>
  export const Plus: FC<SVGProps<SVGSVGElement>>
  export const Minus: FC<SVGProps<SVGSVGElement>>
  export const Edit: FC<SVGProps<SVGSVGElement>>
  export const Trash2: FC<SVGProps<SVGSVGElement>>
  export const Copy: FC<SVGProps<SVGSVGElement>>
  export const ExternalLink: FC<SVGProps<SVGSVGElement>>
  export const Link: FC<SVGProps<SVGSVGElement>>
  export const Bookmark: FC<SVGProps<SVGSVGElement>>
  export const Tag: FC<SVGProps<SVGSVGElement>>
  export const Hash: FC<SVGProps<SVGSVGElement>>
  export const AtSign: FC<SVGProps<SVGSVGElement>>
  export const MessageCircle: FC<SVGProps<SVGSVGElement>>
  export const MessageSquare: FC<SVGProps<SVGSVGElement>>
  export const Send: FC<SVGProps<SVGSVGElement>>
  export const ThumbsUp: FC<SVGProps<SVGSVGElement>>
  export const ThumbsDown: FC<SVGProps<SVGSVGElement>>
  export const Smile: FC<SVGProps<SVGSVGElement>>
  export const Frown: FC<SVGProps<SVGSVGElement>>
  export const Meh: FC<SVGProps<SVGSVGElement>>
  export const Award: FC<SVGProps<SVGSVGElement>>
  export const Trophy: FC<SVGProps<SVGSVGElement>>
  export const Gift: FC<SVGProps<SVGSVGElement>>
  export const Sparkles: FC<SVGProps<SVGSVGElement>>
  export const Zap: FC<SVGProps<SVGSVGElement>>
  export const Target: FC<SVGProps<SVGSVGElement>>
  export const Briefcase: FC<SVGProps<SVGSVGElement>>
  export const Building: FC<SVGProps<SVGSVGElement>>
  export const Users: FC<SVGProps<SVGSVGElement>>
  export const UserPlus: FC<SVGProps<SVGSVGElement>>
  export const UserCheck: FC<SVGProps<SVGSVGElement>>
  export const UserX: FC<SVGProps<SVGSVGElement>>
  export const Shield: FC<SVGProps<SVGSVGElement>>
  export const ShieldCheck: FC<SVGProps<SVGSVGElement>>
  export const ShieldOff: FC<SVGProps<SVGSVGElement>>
  export const Key: FC<SVGProps<SVGSVGElement>>
  export const Database: FC<SVGProps<SVGSVGElement>>
  export const Server: FC<SVGProps<SVGSVGElement>>
  export const Cloud: FC<SVGProps<SVGSVGElement>>
  export const Wifi: FC<SVGProps<SVGSVGElement>>
  export const WifiOff: FC<SVGProps<SVGSVGElement>>
  export const Cpu: FC<SVGProps<SVGSVGElement>>
  export const HardDrive: FC<SVGProps<SVGSVGElement>>
  export const Smartphone: FC<SVGProps<SVGSVGElement>>
  export const Monitor: FC<SVGProps<SVGSVGElement>>
  export const Tablet: FC<SVGProps<SVGSVGElement>>
  export const Camera: FC<SVGProps<SVGSVGElement>>
  export const Video: FC<SVGProps<SVGSVGElement>>
  export const Music: FC<SVGProps<SVGSVGElement>>
  export const Headphones: FC<SVGProps<SVGSVGElement>>
  export const Mic: FC<SVGProps<SVGSVGElement>>
  export const MicOff: FC<SVGProps<SVGSVGElement>>
  export const Volume2: FC<SVGProps<SVGSVGElement>>
  export const VolumeX: FC<SVGProps<SVGSVGElement>>
  export const Play: FC<SVGProps<SVGSVGElement>>
  export const Pause: FC<SVGProps<SVGSVGElement>>
  export const StopCircle: FC<SVGProps<SVGSVGElement>>
  export const SkipBack: FC<SVGProps<SVGSVGElement>>
  export const SkipForward: FC<SVGProps<SVGSVGElement>>
  export const Rewind: FC<SVGProps<SVGSVGElement>>
  export const FastForward: FC<SVGProps<SVGSVGElement>>
  export const RefreshCw: FC<SVGProps<SVGSVGElement>>
  export const RotateCw: FC<SVGProps<SVGSVGElement>>
  export const RotateCcw: FC<SVGProps<SVGSVGElement>>
  export const Loader: FC<SVGProps<SVGSVGElement>>
  export const MoreHorizontal: FC<SVGProps<SVGSVGElement>>
  export const MoreVertical: FC<SVGProps<SVGSVGElement>>
  export const ChevronRight: FC<SVGProps<SVGSVGElement>>
  export const ChevronLeft: FC<SVGProps<SVGSVGElement>>
  export const ChevronUp: FC<SVGProps<SVGSVGElement>>
  export const ArrowRight: FC<SVGProps<SVGSVGElement>>
  export const ArrowLeft: FC<SVGProps<SVGSVGElement>>
  export const ArrowUp: FC<SVGProps<SVGSVGElement>>
  export const ArrowDown: FC<SVGProps<SVGSVGElement>>
  export const CornerUpLeft: FC<SVGProps<SVGSVGElement>>
  export const CornerUpRight: FC<SVGProps<SVGSVGElement>>
  export const CornerDownLeft: FC<SVGProps<SVGSVGElement>>
  export const CornerDownRight: FC<SVGProps<SVGSVGElement>>
  export const Move: FC<SVGProps<SVGSVGElement>>
  export const Maximize2: FC<SVGProps<SVGSVGElement>>
  export const Minimize2: FC<SVGProps<SVGSVGElement>>
  export const XCircle: FC<SVGProps<SVGSVGElement>>
  export const Check: FC<SVGProps<SVGSVGElement>>
  export const HelpCircle: FC<SVGProps<SVGSVGElement>>
  export const Code: FC<SVGProps<SVGSVGElement>>
  export const Terminal: FC<SVGProps<SVGSVGElement>>
  export const GitBranch: FC<SVGProps<SVGSVGElement>>
  export const GitPullRequest: FC<SVGProps<SVGSVGElement>>
  export const GitCommit: FC<SVGProps<SVGSVGElement>>
  export const GitMerge: FC<SVGProps<SVGSVGElement>>
  export const Layers: FC<SVGProps<SVGSVGElement>>
  export const Layout: FC<SVGProps<SVGSVGElement>>
  export const Grid: FC<SVGProps<SVGSVGElement>>
  export const List: FC<SVGProps<SVGSVGElement>>
  export const Sidebar: FC<SVGProps<SVGSVGElement>>
  export const Sliders: FC<SVGProps<SVGSVGElement>>
  export const ToggleLeft: FC<SVGProps<SVGSVGElement>>
  export const ToggleRight: FC<SVGProps<SVGSVGElement>>
  export const Sun: FC<SVGProps<SVGSVGElement>>
  export const Moon: FC<SVGProps<SVGSVGElement>>
  export const Sunrise: FC<SVGProps<SVGSVGElement>>
  export const Sunset: FC<SVGProps<SVGSVGElement>>
  export const CloudRain: FC<SVGProps<SVGSVGElement>>
  export const CloudSnow: FC<SVGProps<SVGSVGElement>>
  export const CloudLightning: FC<SVGProps<SVGSVGElement>>
  export const Wind: FC<SVGProps<SVGSVGElement>>
  export const Droplet: FC<SVGProps<SVGSVGElement>>
  export const Thermometer: FC<SVGProps<SVGSVGElement>>
  export const Compass: FC<SVGProps<SVGSVGElement>>
  export const Navigation: FC<SVGProps<SVGSVGElement>>
  export const Map: FC<SVGProps<SVGSVGElement>>
  export const Flag: FC<SVGProps<SVGSVGElement>>
  export const Anchor: FC<SVGProps<SVGSVGElement>>
  export const Coffee: FC<SVGProps<SVGSVGElement>>
  export const ShoppingCart: FC<SVGProps<SVGSVGElement>>
  export const Package: FC<SVGProps<SVGSVGElement>>
  export const Truck: FC<SVGProps<SVGSVGElement>>
  export const Box: FC<SVGProps<SVGSVGElement>>
  export const Home: FC<SVGProps<SVGSVGElement>>
  export const Book: FC<SVGProps<SVGSVGElement>>
  export const BookOpen: FC<SVGProps<SVGSVGElement>>
  export const FileText: FC<SVGProps<SVGSVGElement>>
  export const File: FC<SVGProps<SVGSVGElement>>
  export const Folder: FC<SVGProps<SVGSVGElement>>
  export const FolderPlus: FC<SVGProps<SVGSVGElement>>
  export const Paperclip: FC<SVGProps<SVGSVGElement>>
  export const Clipboard: FC<SVGProps<SVGSVGElement>>
  export const ClipboardCheck: FC<SVGProps<SVGSVGElement>>
  export const ClipboardCopy: FC<SVGProps<SVGSVGElement>>
  export const ClipboardList: FC<SVGProps<SVGSVGElement>>
  export const CheckSquare: FC<SVGProps<SVGSVGElement>>
  export const Square: FC<SVGProps<SVGSVGElement>>
  export const Circle: FC<SVGProps<SVGSVGElement>>
  export const Hexagon: FC<SVGProps<SVGSVGElement>>
  export const Octagon: FC<SVGProps<SVGSVGElement>>
  export const Triangle: FC<SVGProps<SVGSVGElement>>
  export const Activity: FC<SVGProps<SVGSVGElement>>
  export const Airplay: FC<SVGProps<SVGSVGElement>>
  export const AlertTriangle: FC<SVGProps<SVGSVGElement>>
  export const AlignCenter: FC<SVGProps<SVGSVGElement>>
  export const AlignJustify: FC<SVGProps<SVGSVGElement>>
  export const AlignLeft: FC<SVGProps<SVGSVGElement>>
  export const AlignRight: FC<SVGProps<SVGSVGElement>>
  export const Archive: FC<SVGProps<SVGSVGElement>>
  export const ArrowUpCircle: FC<SVGProps<SVGSVGElement>>
  export const ArrowDownCircle: FC<SVGProps<SVGSVGElement>>
  export const ArrowLeftCircle: FC<SVGProps<SVGSVGElement>>
  export const ArrowRightCircle: FC<SVGProps<SVGSVGElement>>
  export const Aperture: FC<SVGProps<SVGSVGElement>>
  export const Battery: FC<SVGProps<SVGSVGElement>>
  export const BatteryCharging: FC<SVGProps<SVGSVGElement>>
  export const BellOff: FC<SVGProps<SVGSVGElement>>
  export const Bluetooth: FC<SVGProps<SVGSVGElement>>
  export const Bold: FC<SVGProps<SVGSVGElement>>
  export const BookmarkPlus: FC<SVGProps<SVGSVGElement>>
  export const CalendarDays: FC<SVGProps<SVGSVGElement>>
  export const CameraOff: FC<SVGProps<SVGSVGElement>>
  export const Cast: FC<SVGProps<SVGSVGElement>>
  export const CheckCircle2: FC<SVGProps<SVGSVGElement>>
  export const ChevronsDown: FC<SVGProps<SVGSVGElement>>
  export const ChevronsLeft: FC<SVGProps<SVGSVGElement>>
  export const ChevronsRight: FC<SVGProps<SVGSVGElement>>
  export const ChevronsUp: FC<SVGProps<SVGSVGElement>>
  export const Chrome: FC<SVGProps<SVGSVGElement>>
  export const CircleDot: FC<SVGProps<SVGSVGElement>>
  export const CircleEllipsis: FC<SVGProps<SVGSVGElement>>
  export const CircleSlashed: FC<SVGProps<SVGSVGElement>>
  export const CloudDrizzle: FC<SVGProps<SVGSVGElement>>
  export const CloudFog: FC<SVGProps<SVGSVGElement>>
  export const CloudHail: FC<SVGProps<SVGSVGElement>>
  export const CloudMoon: FC<SVGProps<SVGSVGElement>>
  export const CloudSun: FC<SVGProps<SVGSVGElement>>
  export const Cloudy: FC<SVGProps<SVGSVGElement>>
  export const Clover: FC<SVGProps<SVGSVGElement>>
  export const Code2: FC<SVGProps<SVGSVGElement>>
  export const Codepen: FC<SVGProps<SVGSVGElement>>
  export const Codesandbox: FC<SVGProps<SVGSVGElement>>
  export const Columns: FC<SVGProps<SVGSVGElement>>
  export const Command: FC<SVGProps<SVGSVGElement>>
  export const Contact: FC<SVGProps<SVGSVGElement>>
  export const Contrast: FC<SVGProps<SVGSVGElement>>
  export const Cookie: FC<SVGProps<SVGSVGElement>>
  export const CopyPlus: FC<SVGProps<SVGSVGElement>>
  export const CornerLeftDown: FC<SVGProps<SVGSVGElement>>
  export const CornerLeftUp: FC<SVGProps<SVGSVGElement>>
  export const CornerRightDown: FC<SVGProps<SVGSVGElement>>
  export const CornerRightUp: FC<SVGProps<SVGSVGElement>>
  export const Cpu: FC<SVGProps<SVGSVGElement>>
  export const CreativeCommons: FC<SVGProps<SVGSVGElement>>
  export const Crop: FC<SVGProps<SVGSVGElement>>
  export const Crosshair: FC<SVGProps<SVGSVGElement>>
  export const Crown: FC<SVGProps<SVGSVGElement>>
  export const Cube: FC<SVGProps<SVGSVGElement>>
  export const Currency: FC<SVGProps<SVGSVGElement>>
  export const Diamond: FC<SVGProps<SVGSVGElement>>
  export const Dice1: FC<SVGProps<SVGSVGElement>>
  export const Dice2: FC<SVGProps<SVGSVGElement>>
  export const Dice3: FC<SVGProps<SVGSVGElement>>
  export const Dice4: FC<SVGProps<SVGSVGElement>>
  export const Dice5: FC<SVGProps<SVGSVGElement>>
  export const Dice6: FC<SVGProps<SVGSVGElement>>
  export const Disc: FC<SVGProps<SVGSVGElement>>
  export const Divide: FC<SVGProps<SVGSVGElement>>
  export const DivideCircle: FC<SVGProps<SVGSVGElement>>
  export const DivideSquare: FC<SVGProps<SVGSVGElement>>
  export const Dribbble: FC<SVGProps<SVGSVGElement>>
  export const Droplets: FC<SVGProps<SVGSVGElement>>
  export const Ear: FC<SVGProps<SVGSVGElement>>
  export const EarOff: FC<SVGProps<SVGSVGElement>>
  export const Edit2: FC<SVGProps<SVGSVGElement>>
  export const Edit3: FC<SVGProps<SVGSVGElement>>
  export const Equal: FC<SVGProps<SVGSVGElement>>
  export const EqualNot: FC<SVGProps<SVGSVGElement>>
  export const EyeDropper: FC<SVGProps<SVGSVGElement>>
  export const Facebook: FC<SVGProps<SVGSVGElement>>
  export const Figma: FC<SVGProps<SVGSVGElement>>
  export const FileArchive: FC<SVGProps<SVGSVGElement>>
  export const FileAudio: FC<SVGProps<SVGSVGElement>>
  export const FileCode: FC<SVGProps<SVGSVGElement>>
  export const FileImage: FC<SVGProps<SVGSVGElement>>
  export const FileVideo: FC<SVGProps<SVGSVGElement>>
  export const Film: FC<SVGProps<SVGSVGElement>>
  export const FilterX: FC<SVGProps<SVGSVGElement>>
  export const Fingerprint: FC<SVGProps<SVGSVGElement>>
  export const Fish: FC<SVGProps<SVGSVGElement>>
  export const FlagTriangleLeft: FC<SVGProps<SVGSVGElement>>
  export const FlagTriangleRight: FC<SVGProps<SVGSVGElement>>
  export const Flame: FC<SVGProps<SVGSVGElement>>
  export const Flashlight: FC<SVGProps<SVGSVGElement>>
  export const FlashlightOff: FC<SVGProps<SVGSVGElement>>
  export const FlaskConical: FC<SVGProps<SVGSVGElement>>
  export const FlaskRound: FC<SVGProps<SVGSVGElement>>
  export const FlipHorizontal: FC<SVGProps<SVGSVGElement>>
  export const FlipVertical: FC<SVGProps<SVGSVGElement>>
  export const Flower: FC<SVGProps<SVGSVGElement>>
  export const Flower2: FC<SVGProps<SVGSVGElement>>
  export const Focus: FC<SVGProps<SVGSVGElement>>
  export const FoldHorizontal: FC<SVGProps<SVGSVGElement>>
  export const FoldVertical: FC<SVGProps<SVGSVGElement>>
  export const FolderMinus: FC<SVGProps<SVGSVGElement>>
  export const FormInput: FC<SVGProps<SVGSVGElement>>
  export const Forward: FC<SVGProps<SVGSVGElement>>
  export const Frame: FC<SVGProps<SVGSVGElement>>
  export const Framer: FC<SVGProps<SVGSVGElement>>
  export const Function: FC<SVGProps<SVGSVGElement>>
  export const Gamepad: FC<SVGProps<SVGSVGElement>>
  export const Gamepad2: FC<SVGProps<SVGSVGElement>>
  export const Gauge: FC<SVGProps<SVGSVGElement>>
  export const Gavel: FC<SVGProps<SVGSVGElement>>
  export const Gem: FC<SVGProps<SVGSVGElement>>
  export const Ghost: FC<SVGProps<SVGSVGElement>>
  export const Gift: FC<SVGProps<SVGSVGElement>>
  export const GitCompare: FC<SVGProps<SVGSVGElement>>
  export const GitFork: FC<SVGProps<SVGSVGElement>>
  export const Gitlab: FC<SVGProps<SVGSVGElement>>
  export const GlassWater: FC<SVGProps<SVGSVGElement>>
  export const Glasses: FC<SVGProps<SVGSVGElement>>
  export const Grab: FC<SVGProps<SVGSVGElement>>
  export const GraduationCap: FC<SVGProps<SVGSVGElement>>
  export const Grid3x3: FC<SVGProps<SVGSVGElement>>
  export const GripHorizontal: FC<SVGProps<SVGSVGElement>>
  export const GripVertical: FC<SVGProps<SVGSVGElement>>
  export const Hammer: FC<SVGProps<SVGSVGElement>>
  export const Hand: FC<SVGProps<SVGSVGElement>>
  export const HandMetal: FC<SVGProps<SVGSVGElement>>
  export const HardHat: FC<SVGProps<SVGSVGElement>>
  export const Hash: FC<SVGProps<SVGSVGElement>>
  export const Haze: FC<SVGProps<SVGSVGElement>>
  export const HdmiPort: FC<SVGProps<SVGSVGElement>>
  export const Heading: FC<SVGProps<SVGSVGElement>>
  export const Heading1: FC<SVGProps<SVGSVGElement>>
  export const Heading2: FC<SVGProps<SVGSVGElement>>
  export const Heading3: FC<SVGProps<SVGSVGElement>>
  export const Heading4: FC<SVGProps<SVGSVGElement>>
  export const Heading5: FC<SVGProps<SVGSVGElement>>
  export const Heading6: FC<SVGProps<SVGSVGElement>>
  export const Headset: FC<SVGProps<SVGSVGElement>>
  export const HeartCrack: FC<SVGProps<SVGSVGElement>>
  export const HeartHandshake: FC<SVGProps<SVGSVGElement>>
  export const HeartOff: FC<SVGProps<SVGSVGElement>>
  export const HeartPulse: FC<SVGProps<SVGSVGElement>>
  export const HelpCircle: FC<SVGProps<SVGSVGElement>>
  export const Highlighter: FC<SVGProps<SVGSVGElement>>
  export const History: FC<SVGProps<SVGSVGElement>>
  export const Home: FC<SVGProps<SVGSVGElement>>
  export const Hop: FC<SVGProps<SVGSVGElement>>
  export const HopOff: FC<SVGProps<SVGSVGElement>>
  export const Hotel: FC<SVGProps<SVGSVGElement>>
  export const Hourglass: FC<SVGProps<SVGSVGElement>>
  export const IceCream: FC<SVGProps<SVGSVGElement>>
  export const Image: FC<SVGProps<SVGSVGElement>>
  export const ImageOff: FC<SVGProps<SVGSVGElement>>
  export const Import: FC<SVGProps<SVGSVGElement>>
  export const Inbox: FC<SVGProps<SVGSVGElement>>
  export const Indent: FC<SVGProps<SVGSVGElement>>
  export const IndianRupee: FC<SVGProps<SVGSVGElement>>
  export const Infinity: FC<SVGProps<SVGSVGElement>>
  export const Info: FC<SVGProps<SVGSVGElement>>
  export const Instagram: FC<SVGProps<SVGSVGElement>>
  export const Italic: FC<SVGProps<SVGSVGElement>>
  export const IterationCcw: FC<SVGProps<SVGSVGElement>>
  export const IterationCw: FC<SVGProps<SVGSVGElement>>
  export const JapaneseYen: FC<SVGProps<SVGSVGElement>>
  export const Joystick: FC<SVGProps<SVGSVGElement>>
  export const Kanban: FC<SVGProps<SVGSVGElement>>
  export const KeyRound: FC<SVGProps<SVGSVGElement>>
  export const KeySquare: FC<SVGProps<SVGSVGElement>>
  export const Keyboard: FC<SVGProps<SVGSVGElement>>
  export const Lamp: FC<SVGProps<SVGSVGElement>>
  export const LampCeiling: FC<SVGProps<SVGSVGElement>>
  export const LampDesk: FC<SVGProps<SVGSVGElement>>
  export const LampFloor: FC<SVGProps<SVGSVGElement>>
  export const LampWallDown: FC<SVGProps<SVGSVGElement>>
  export const LampWallUp: FC<SVGProps<SVGSVGElement>>
  export const Landmark: FC<SVGProps<SVGSVGElement>>
  export const Languages: FC<SVGProps<SVGSVGElement>>
  export const Laptop: FC<SVGProps<SVGSVGElement>>
  export const Laptop2: FC<SVGProps<SVGSVGElement>>
  export const Lasso: FC<SVGProps<SVGSVGElement>>
  export const LassoSelect: FC<SVGProps<SVGSVGElement>>
  export const Laugh: FC<SVGProps<SVGSVGElement>>
  export const Layers2: FC<SVGProps<SVGSVGElement>>
  export const Layers3: FC<SVGProps<SVGSVGElement>>
  export const LayoutDashboard: FC<SVGProps<SVGSVGElement>>
  export const LayoutGrid: FC<SVGProps<SVGSVGElement>>
  export const LayoutList: FC<SVGProps<SVGSVGElement>>
  export const LayoutPanelLeft: FC<SVGProps<SVGSVGElement>>
  export const LayoutPanelTop: FC<SVGProps<SVGSVGElement>>
  export const LayoutTemplate: FC<SVGProps<SVGSVGElement>>
  export const Leaf: FC<SVGProps<SVGSVGElement>>
  export const LeafyGreen: FC<SVGProps<SVGSVGElement>>
  export const Library: FC<SVGProps<SVGSVGElement>>
  export const LifeBuoy: FC<SVGProps<SVGSVGElement>>
  export const Ligature: FC<SVGProps<SVGSVGElement>>
  export const Lightbulb: FC<SVGProps<SVGSVGElement>>
  export const LightbulbOff: FC<SVGProps<SVGSVGElement>>
  export const LineChart: FC<SVGProps<SVGSVGElement>>
  export const Link2: FC<SVGProps<SVGSVGElement>>
  export const Link2Off: FC<SVGProps<SVGSVGElement>>
  export const Linkedin: FC<SVGProps<SVGSVGElement>>
  export const ListChecks: FC<SVGProps<SVGSVGElement>>
  export const ListEnd: FC<SVGProps<SVGSVGElement>>
  export const ListFilter: FC<SVGProps<SVGSVGElement>>
  export const ListMinus: FC<SVGProps<SVGSVGElement>>
  export const ListMusic: FC<SVGProps<SVGSVGElement>>
  export const ListOrdered: FC<SVGProps<SVGSVGElement>>
  export const ListPlus: FC<SVGProps<SVGSVGElement>>
  export const ListRestart: FC<SVGProps<SVGSVGElement>>
  export const ListStart: FC<SVGProps<SVGSVGElement>>
  export const ListTodo: FC<SVGProps<SVGSVGElement>>
  export const ListTree: FC<SVGProps<SVGSVGElement>>
  export const ListVideo: FC<SVGProps<SVGSVGElement>>
  export const ListX: FC<SVGProps<SVGSVGElement>>
  export const Loader2: FC<SVGProps<SVGSVGElement>>
  export const Locate: FC<SVGProps<SVGSVGElement>>
  export const LocateFixed: FC<SVGProps<SVGSVGElement>>
  export const LocateOff: FC<SVGProps<SVGSVGElement>>
  export const LockKeyhole: FC<SVGProps<SVGSVGElement>>
  export const LogIn: FC<SVGProps<SVGSVGElement>>
  export const LogOut: FC<SVGProps<SVGSVGElement>>
  export const Mails: FC<SVGProps<SVGSVGElement>>
  export const MapPinned: FC<SVGProps<SVGSVGElement>>
  export const Maximize: FC<SVGProps<SVGSVGElement>>
  export const Medal: FC<SVGProps<SVGSVGElement>>
  export const Megaphone: FC<SVGProps<SVGSVGElement>>
  export const MegaphoneOff: FC<SVGProps<SVGSVGElement>>
  export const Meh: FC<SVGProps<SVGSVGElement>>
  export const MemoryStick: FC<SVGProps<SVGSVGElement>>
  export const MenuSquare: FC<SVGProps<SVGSVGElement>>
  export const Merge: FC<SVGProps<SVGSVGElement>>
  export const MessageCircle: FC<SVGProps<SVGSVGElement>>
  export const MessageCircleDashed: FC<SVGProps<SVGSVGElement>>
  export const MessageCircleHeart: FC<SVGProps<SVGSVGElement>>
  export const MessageCircleMore: FC<SVGProps<SVGSVGElement>>
  export const MessageCircleOff: FC<SVGProps<SVGSVGElement>>
  export const MessageCirclePlus: FC<SVGProps<SVGSVGElement>>
  export const MessageCircleQuestion: FC<SVGProps<SVGSVGElement>>
  export const MessageCircleReply: FC<SVGProps<SVGSVGElement>>
  export const MessageCircleWarning: FC<SVGProps<SVGSVGElement>>
  export const MessageCircleX: FC<SVGProps<SVGSVGElement>>
  export const MessageSquare: FC<SVGProps<SVGSVGElement>>
  export const MessageSquareDashed: FC<SVGProps<SVGSVGElement>>
  export const MessageSquareDiff: FC<SVGProps<SVGSVGElement>>
  export const MessageSquareDot: FC<SVGProps<SVGSVGElement>>
  export const MessageSquareHeart: FC<SVGProps<SVGSVGElement>>
  export const MessageSquareMore: FC<SVGProps<SVGSVGElement>>
  export const MessageSquareOff: FC<SVGProps<SVGSVGElement>>
  export const MessageSquarePlus: FC<SVGProps<SVGSVGElement>>
  export const MessageSquareQuote: FC<SVGProps<SVGSVGElement>>
  export const MessageSquareReply: FC<SVGProps<SVGSVGElement>>
  export const MessageSquareShare: FC<SVGProps<SVGSVGElement>>
  export const MessageSquareText: FC<SVGProps<SVGSVGElement>>
  export const MessageSquareWarning: FC<SVGProps<SVGSVGElement>>
  export const MessageSquareX: FC<SVGProps<SVGSVGElement>>
  export const MessagesSquare: FC<SVGProps<SVGSVGElement>>
  export const Mic2: FC<SVGProps<SVGSVGElement>>
  export const MicOff: FC<SVGProps<SVGSVGElement>>
  export const Microscope: FC<SVGProps<SVGSVGElement>>
  export const Microwave: FC<SVGProps<SVGSVGElement>>
  export const Milestone: FC<SVGProps<SVGSVGElement>>
  export const Milk: FC<SVGProps<SVGSVGElement>>
  export const MilkOff: FC<SVGProps<SVGSVGElement>>
  export const Minimize: FC<SVGProps<SVGSVGElement>>
  export const MinusCircle: FC<SVGProps<SVGSVGElement>>
  export const MinusSquare: FC<SVGProps<SVGSVGElement>>
  export const MonitorCheck: FC<SVGProps<SVGSVGElement>>
  export const MonitorDot: FC<SVGProps<SVGSVGElement>>
  export const MonitorDown: FC<SVGProps<SVGSVGElement>>
  export const MonitorOff: FC<SVGProps<SVGSVGElement>>
  export const MonitorPause: FC<SVGProps<SVGSVGElement>>
  export const MonitorPlay: FC<SVGProps<SVGSVGElement>>
  export const MonitorSmartphone: FC<SVGProps<SVGSVGElement>>
  export const MonitorSpeaker: FC<SVGProps<SVGSVGElement>>
  export const MonitorStop: FC<SVGProps<SVGSVGElement>>
  export const MonitorUp: FC<SVGProps<SVGSVGElement>>
  export const MonitorX: FC<SVGProps<SVGSVGElement>>
  export const MoonStar: FC<SVGProps<SVGSVGElement>>
  export const Mountain: FC<SVGProps<SVGSVGElement>>
  export const MountainSnow: FC<SVGProps<SVGSVGElement>>
  export const Mouse: FC<SVGProps<SVGSVGElement>>
  export const MousePointer: FC<SVGProps<SVGSVGElement>>
  export const MousePointer2: FC<SVGProps<SVGSVGElement>>
  export const MousePointerClick: FC<SVGProps<SVGSVGElement>>
  export const MousePointerSquare: FC<SVGProps<SVGSVGElement>>
  export const Move3d: FC<SVGProps<SVGSVGElement>>
  export const MoveDiagonal: FC<SVGProps<SVGSVGElement>>
  export const MoveDiagonal2: FC<SVGProps<SVGSVGElement>>
  export const MoveHorizontal: FC<SVGProps<SVGSVGElement>>
  export const MoveVertical: FC<SVGProps<SVGSVGElement>>
  export const Music2: FC<SVGProps<SVGSVGElement>>
  export const Music3: FC<SVGProps<SVGSVGElement>>
  export const Music4: FC<SVGProps<SVGSVGElement>>
  export const Navigation2: FC<SVGProps<SVGSVGElement>>
  export const Navigation2Off: FC<SVGProps<SVGSVGElement>>
  export const Network: FC<SVGProps<SVGSVGElement>>
  export const Newspaper: FC<SVGProps<SVGSVGElement>>
  export const Nfc: FC<SVGProps<SVGSVGElement>>
  export const Notebook: FC<SVGProps<SVGSVGElement>>
  export const NotebookPen: FC<SVGProps<SVGSVGElement>>
  export const NotebookTabs: FC<SVGProps<SVGSVGElement>>
  export const NotepadText: FC<SVGProps<SVGSVGElement>>
  export const Nut: FC<SVGProps<SVGSVGElement>>
  export const NutOff: FC<SVGProps<SVGSVGElement>>
  export const OctagonAlert: FC<SVGProps<SVGSVGElement>>
  export const OctagonPause: FC<SVGProps<SVGSVGElement>>
  export const Option: FC<SVGProps<SVGSVGElement>>
  export const Orbit: FC<SVGProps<SVGSVGElement>>
  export const Package2: FC<SVGProps<SVGSVGElement>>
  export const PackageCheck: FC<SVGProps<SVGSVGElement>>
  export const PackageMinus: FC<SVGProps<SVGSVGElement>>
  export const PackageOpen: FC<SVGProps<SVGSVGElement>>
  export const PackagePlus: FC<SVGProps<SVGSVGElement>>
  export const PackageSearch: FC<SVGProps<SVGSVGElement>>
  export const PackageX: FC<SVGProps<SVGSVGElement>>
  export const PaintBucket: FC<SVGProps<SVGSVGElement>>
  export const Paintbrush: FC<SVGProps<SVGSVGElement>>
  export const Paintbrush2: FC<SVGProps<SVGSVGElement>>
  export const Palette: FC<SVGProps<SVGSVGElement>>
  export const PanelBottom: FC<SVGProps<SVGSVGElement>>
  export const PanelBottomClose: FC<SVGProps<SVGSVGElement>>
  export const PanelBottomInactive: FC<SVGProps<SVGSVGElement>>
  export const PanelBottomOpen: FC<SVGProps<SVGSVGElement>>
  export const PanelLeft: FC<SVGProps<SVGSVGElement>>
  export const PanelLeftClose: FC<SVGProps<SVGSVGElement>>
  export const PanelLeftInactive: FC<SVGProps<SVGSVGElement>>
  export const PanelLeftOpen: FC<SVGProps<SVGSVGElement>>
  export const PanelRight: FC<SVGProps<SVGSVGElement>>
  export const PanelRightClose: FC<SVGProps<SVGSVGElement>>
  export const PanelRightInactive: FC<SVGProps<SVGSVGElement>>
  export const PanelRightOpen: FC<SVGProps<SVGSVGElement>>
  export const PanelTop: FC<SVGProps<SVGSVGElement>>
  export const PanelTopClose: FC<SVGProps<SVGSVGElement>>
  export const PanelTopInactive: FC<SVGProps<SVGSVGElement>>
  export const PanelTopOpen: FC<SVGProps<SVGSVGElement>>
  export const Paperclip: FC<SVGProps<SVGSVGElement>>
  export const Parentheses: FC<SVGProps<SVGSVGElement>>
  export const ParkingCircle: FC<SVGProps<SVGSVGElement>>
  export const ParkingCircleOff: FC<SVGProps<SVGSVGElement>>
  export const ParkingMeter: FC<SVGProps<SVGSVGElement>>
  export const PartyPopper: FC<SVGProps<SVGSVGElement>>
  export const PauseCircle: FC<SVGProps<SVGSVGElement>>
  export const PauseOctagon: FC<SVGProps<SVGSVGElement>>
  export const PcCase: FC<SVGProps<SVGSVGElement>>
  export const Pen: FC<SVGProps<SVGSVGElement>>
  export const PenLine: FC<SVGProps<SVGSVGElement>>
  export const PenSquare: FC<SVGProps<SVGSVGElement>>
  export const PenTool: FC<SVGProps<SVGSVGElement>>
  export const Pencil: FC<SVGProps<SVGSVGElement>>
  export const PencilLine: FC<SVGProps<SVGSVGElement>>
  export const PencilRuler: FC<SVGProps<SVGSVGElement>>
  export const Percent: FC<SVGProps<SVGSVGElement>>
  export const PercentCircle: FC<SVGProps<SVGSVGElement>>
  export const PercentDiamond: FC<SVGProps<SVGSVGElement>>
  export const PercentSquare: FC<SVGProps<SVGSVGElement>>
  export const PhoneCall: FC<SVGProps<SVGSVGElement>>
  export const PhoneForwarded: FC<SVGProps<SVGSVGElement>>
  export const PhoneIncoming: FC<SVGProps<SVGSVGElement>>
  export const PhoneMissed: FC<SVGProps<SVGSVGElement>>
  export const PhoneOff: FC<SVGProps<SVGSVGElement>>
  export const PhoneOutgoing: FC<SVGProps<SVGSVGElement>>
  export const Pi: FC<SVGProps<SVGSVGElement>>
  export const PiSquare: FC<SVGProps<SVGSVGElement>>
  export const PictureInPicture: FC<SVGProps<SVGSVGElement>>
  export const PictureInPicture2: FC<SVGProps<SVGSVGElement>>
  export const PieChart: FC<SVGProps<SVGSVGElement>>
  export const PiggyBank: FC<SVGProps<SVGSVGElement>>
  export const Pilcrow: FC<SVGProps<SVGSVGElement>>
  export const PilcrowSquare: FC<SVGProps<SVGSVGElement>>
  export const Pill: FC<SVGProps<SVGSVGElement>>
  export const Pin: FC<SVGProps<SVGSVGElement>>
  export const PinOff: FC<SVGProps<SVGSVGElement>>
  export const Pipette: FC<SVGProps<SVGSVGElement>>
  export const Pizza: FC<SVGProps<SVGSVGElement>>
  export const Plane: FC<SVGProps<SVGSVGElement>>
  export const PlaneLanding: FC<SVGProps<SVGSVGElement>>
  export const PlaneTakeoff: FC<SVGProps<SVGSVGElement>>
  export const PlayCircle: FC<SVGProps<SVGSVGElement>>
  export const PlaySquare: FC<SVGProps<SVGSVGElement>>
  export const Plug: FC<SVGProps<SVGSVGElement>>
  export const Plug2: FC<SVGProps<SVGSVGElement>>
  export const PlugZap: FC<SVGProps<SVGSVGElement>>
  export const PlusCircle: FC<SVGProps<SVGSVGElement>>
  export const PlusSquare: FC<SVGProps<SVGSVGElement>>
  export const Pocket: FC<SVGProps<SVGSVGElement>>
  export const PocketKnife: FC<SVGProps<SVGSVGElement>>
  export const Podcast: FC<SVGProps<SVGSVGElement>>
  export const Pointer: FC<SVGProps<SVGSVGElement>>
  export const Popcorn: FC<SVGProps<SVGSVGElement>>
  export const Popsicle: FC<SVGProps<SVGSVGElement>>
  export const PoundSterling: FC<SVGProps<SVGSVGElement>>
  export const Power: FC<SVGProps<SVGSVGElement>>
  export const PowerOff: FC<SVGProps<SVGSVGElement>>
  export const Presentation: FC<SVGProps<SVGSVGElement>>
  export const Printer: FC<SVGProps<SVGSVGElement>>
  export const Projector: FC<SVGProps<SVGSVGElement>>
  export const Pulse: FC<SVGProps<SVGSVGElement>>
  export const Pyramid: FC<SVGProps<SVGSVGElement>>
  export const QrCode: FC<SVGProps<SVGSVGElement>>
  export const Quote: FC<SVGProps<SVGSVGElement>>
  export const Radar: FC<SVGProps<SVGSVGElement>>
  export const Radiation: FC<SVGProps<SVGSVGElement>>
  export const Radio: FC<SVGProps<SVGSVGElement>>
  export const RadioReceiver: FC<SVGProps<SVGSVGElement>>
  export const RadioTower: FC<SVGProps<SVGSVGElement>>
  export const Radius: FC<SVGProps<SVGSVGElement>>
  export const RailSymbol: FC<SVGProps<SVGSVGElement>>
  export const Rainbow: FC<SVGProps<SVGSVGElement>>
  export const Rat: FC<SVGProps<SVGSVGElement>>
  export const Ratio: FC<SVGProps<SVGSVGElement>>
  export const Receipt: FC<SVGProps<SVGSVGElement>>
  export const RectangleHorizontal: FC<SVGProps<SVGSVGElement>>
  export const RectangleVertical: FC<SVGProps<SVGSVGElement>>
  export const Recycle: FC<SVGProps<SVGSVGElement>>
  export const Redo: FC<SVGProps<SVGSVGElement>>
  export const Redo2: FC<SVGProps<SVGSVGElement>>
  export const RedoDot: FC<SVGProps<SVGSVGElement>>
  export const RefreshCcw: FC<SVGProps<SVGSVGElement>>
  export const RefreshCw: FC<SVGProps<SVGSVGElement>>
  export const Refrigerator: FC<SVGProps<SVGSVGElement>>
  export const Regex: FC<SVGProps<SVGSVGElement>>
  export const RemoveFormatting: FC<SVGProps<SVGSVGElement>>
  export const Repeat: FC<SVGProps<SVGSVGElement>>
  export const Repeat1: FC<SVGProps<SVGSVGElement>>
  export const Repeat2: FC<SVGProps<SVGSVGElement>>
  export const Replace: FC<SVGProps<SVGSVGElement>>
  export const ReplaceAll: FC<SVGProps<SVGSVGElement>>
  export const Reply: FC<SVGProps<SVGSVGElement>>
  export const ReplyAll: FC<SVGProps<SVGSVGElement>>
  export const Rewind: FC<SVGProps<SVGSVGElement>>
  export const Rocket: FC<SVGProps<SVGSVGElement>>
  export const RockingChair: FC<SVGProps<SVGSVGElement>>
  export const RollerCoaster: FC<SVGProps<SVGSVGElement>>
  export const Rotate3d: FC<SVGProps<SVGSVGElement>>
  export const Route: FC<SVGProps<SVGSVGElement>>
  export const RouteOff: FC<SVGProps<SVGSVGElement>>
  export const Router: FC<SVGProps<SVGSVGElement>>
  export const Rows: FC<SVGProps<SVGSVGElement>>
  export const Rss: FC<SVGProps<SVGSVGElement>>
  export const Ruler: FC<SVGProps<SVGSVGElement>>
  export const RussianRuble: FC<SVGProps<SVGSVGElement>>
  export const Sailboat: FC<SVGProps<SVGSVGElement>>
  export const Salad: FC<SVGProps<SVGSVGElement>>
  export const Sandwich: FC<SVGProps<SVGSVGElement>>
  export const Satellite: FC<SVGProps<SVGSVGElement>>
  export const SatelliteDish: FC<SVGProps<SVGSVGElement>>
  export const Save: FC<SVGProps<SVGSVGElement>>
  export const SaveAll: FC<SVGProps<SVGSVGElement>>
  export const Scale: FC<SVGProps<SVGSVGElement>>
  export const Scale3d: FC<SVGProps<SVGSVGElement>>
  export const Scaling: FC<SVGProps<SVGSVGElement>>
  export const Scan: FC<SVGProps<SVGSVGElement>>
  export const ScanBarcode: FC<SVGProps<SVGSVGElement>>
  export const ScanEye: FC<SVGProps<SVGSVGElement>>
  export const ScanFace: FC<SVGProps<SVGSVGElement>>
  export const ScanLine: FC<SVGProps<SVGSVGElement>>
  export const ScanSearch: FC<SVGProps<SVGSVGElement>>
  export const ScanText: FC<SVGProps<SVGSVGElement>>
  export const School: FC<SVGProps<SVGSVGElement>>
  export const Scissors: FC<SVGProps<SVGSVGElement>>
  export const ScissorsLineDashed: FC<SVGProps<SVGSVGElement>>
  export const ScreenShare: FC<SVGProps<SVGSVGElement>>
  export const ScreenShareOff: FC<SVGProps<SVGSVGElement>>
  export const Scroll: FC<SVGProps<SVGSVGElement>>
  export const ScrollText: FC<SVGProps<SVGSVGElement>>
  export const SearchCheck: FC<SVGProps<SVGSVGElement>>
  export const SearchCode: FC<SVGProps<SVGSVGElement>>
  export const SearchSlash: FC<SVGProps<SVGSVGElement>>
  export const SearchX: FC<SVGProps<SVGSVGElement>>
  export const SendHorizonal: FC<SVGProps<SVGSVGElement>>
  export const SendToBack: FC<SVGProps<SVGSVGElement>>
  export const SeparatorHorizontal: FC<SVGProps<SVGSVGElement>>
  export const SeparatorVertical: FC<SVGProps<SVGSVGElement>>
  export const ServerCog: FC<SVGProps<SVGSVGElement>>
  export const ServerCrash: FC<SVGProps<SVGSVGElement>>
  export const ServerOff: FC<SVGProps<SVGSVGElement>>
  export const Settings2: FC<SVGProps<SVGSVGElement>>
  export const Shapes: FC<SVGProps<SVGSVGElement>>
  export const Share: FC<SVGProps<SVGSVGElement>>
  export const Sheet: FC<SVGProps<SVGSVGElement>>
  export const ShieldAlert: FC<SVGProps<SVGSVGElement>>
  export const ShieldBan: FC<SVGProps<SVGSVGElement>>
  export const ShieldCheck: FC<SVGProps<SVGSVGElement>>
  export const ShieldEllipsis: FC<SVGProps<SVGSVGElement>>
  export const ShieldHalf: FC<SVGProps<SVGSVGElement>>
  export const ShieldMinus: FC<SVGProps<SVGSVGElement>>
  export const ShieldOff: FC<SVGProps<SVGSVGElement>>
  export const ShieldPlus: FC<SVGProps<SVGSVGElement>>
  export const ShieldQuestion: FC<SVGProps<SVGSVGElement>>
  export const ShieldX: FC<SVGProps<SVGSVGElement>>
  export const Ship: FC<SVGProps<SVGSVGElement>>
  export const ShipWheel: FC<SVGProps<SVGSVGElement>>
  export const Shirt: FC<SVGProps<SVGSVGElement>>
  export const ShoppingBag: FC<SVGProps<SVGSVGElement>>
  export const ShoppingBasket: FC<SVGProps<SVGSVGElement>>
  export const ShoppingCart: FC<SVGProps<SVGSVGElement>>
  export const Shovel: FC<SVGProps<SVGSVGElement>>
  export const ShowerHead: FC<SVGProps<SVGSVGElement>>
  export const Shrink: FC<SVGProps<SVGSVGElement>>
  export const Shrub: FC<SVGProps<SVGSVGElement>>
  export const Shuffle: FC<SVGProps<SVGSVGElement>>
  export const Sigma: FC<SVGProps<SVGSVGElement>>
  export const SigmaSquare: FC<SVGProps<SVGSVGElement>>
  export const Signal: FC<SVGProps<SVGSVGElement>>
  export const SignalHigh: FC<SVGProps<SVGSVGElement>>
  export const SignalLow: FC<SVGProps<SVGSVGElement>>
  export const SignalMedium: FC<SVGProps<SVGSVGElement>>
  export const SignalZero: FC<SVGProps<SVGSVGElement>>
  export const Signpost: FC<SVGProps<SVGSVGElement>>
  export const SignpostBig: FC<SVGProps<SVGSVGElement>>
  export const Siren: FC<SVGProps<SVGSVGElement>>
  export const SkipBack: FC<SVGProps<SVGSVGElement>>
  export const SkipForward: FC<SVGProps<SVGSVGElement>>
  export const Skull: FC<SVGProps<SVGSVGElement>>
  export const Slack: FC<SVGProps<SVGSVGElement>>
  export const Slash: FC<SVGProps<SVGSVGElement>>
  export const Slice: FC<SVGProps<SVGSVGElement>>
  export const SlidersHorizontal: FC<SVGProps<SVGSVGElement>>
  export const SlidersVertical: FC<SVGProps<SVGSVGElement>>
  export const SmartphoneCharging: FC<SVGProps<SVGSVGElement>>
  export const SmartphoneNfc: FC<SVGProps<SVGSVGElement>>
  export const SmilePlus: FC<SVGProps<SVGSVGElement>>
  export const Snail: FC<SVGProps<SVGSVGElement>>
  export const Snowflake: FC<SVGProps<SVGSVGElement>>
  export const Sofa: FC<SVGProps<SVGSVGElement>>
  export const SortAsc: FC<SVGProps<SVGSVGElement>>
  export const SortDesc: FC<SVGProps<SVGSVGElement>>
  export const Soup: FC<SVGProps<SVGSVGElement>>
  export const Space: FC<SVGProps<SVGSVGElement>>
  export const Spade: FC<SVGProps<SVGSVGElement>>
  export const Sparkle: FC<SVGProps<SVGSVGElement>>
  export const Sparkles: FC<SVGProps<SVGSVGElement>>
  export const Speaker: FC<SVGProps<SVGSVGElement>>
  export const SpellCheck: FC<SVGProps<SVGSVGElement>>
  export const SpellCheck2: FC<SVGProps<SVGSVGElement>>
  export const Spline: FC<SVGProps<SVGSVGElement>>
  export const Split: FC<SVGProps<SVGSVGElement>>
  export const SprayCan: FC<SVGProps<SVGSVGElement>>
  export const Sprout: FC<SVGProps<SVGSVGElement>>
  export const SquareActivity: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowDown: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowDownLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowDownRight: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowOutDownLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowOutDownRight: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowOutUpLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowOutUpRight: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowRight: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowUp: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowUpLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowUpRight: FC<SVGProps<SVGSVGElement>>
  export const SquareAsterisk: FC<SVGProps<SVGSVGElement>>
  export const SquareBottomDashedScissors: FC<SVGProps<SVGSVGElement>>
  export const SquareChartGantt: FC<SVGProps<SVGSVGElement>>
  export const SquareCheck: FC<SVGProps<SVGSVGElement>>
  export const SquareCheckBig: FC<SVGProps<SVGSVGElement>>
  export const SquareChevronDown: FC<SVGProps<SVGSVGElement>>
  export const SquareChevronLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareChevronRight: FC<SVGProps<SVGSVGElement>>
  export const SquareChevronUp: FC<SVGProps<SVGSVGElement>>
  export const SquareCode: FC<SVGProps<SVGSVGElement>>
  export const SquareDashed: FC<SVGProps<SVGSVGElement>>
  export const SquareDashedBottomCode: FC<SVGProps<SVGSVGElement>>
  export const SquareDashedBottom: FC<SVGProps<SVGSVGElement>>
  export const SquareDashedKanban: FC<SVGProps<SVGSVGElement>>
  export const SquareDashedMousePointer: FC<SVGProps<SVGSVGElement>>
  export const SquareDivide: FC<SVGProps<SVGSVGElement>>
  export const SquareDot: FC<SVGProps<SVGSVGElement>>
  export const SquareEqual: FC<SVGProps<SVGSVGElement>>
  export const SquareFunction: FC<SVGProps<SVGSVGElement>>
  export const SquareKanban: FC<SVGProps<SVGSVGElement>>
  export const SquareLibrary: FC<SVGProps<SVGSVGElement>>
  export const SquareM: FC<SVGProps<SVGSVGElement>>
  export const SquareMenu: FC<SVGProps<SVGSVGElement>>
  export const SquareMinus: FC<SVGProps<SVGSVGElement>>
  export const SquareMousePointer: FC<SVGProps<SVGSVGElement>>
  export const SquareParking: FC<SVGProps<SVGSVGElement>>
  export const SquareParkingOff: FC<SVGProps<SVGSVGElement>>
  export const SquarePen: FC<SVGProps<SVGSVGElement>>
  export const SquarePercent: FC<SVGProps<SVGSVGElement>>
  export const SquarePi: FC<SVGProps<SVGSVGElement>>
  export const SquarePilcrow: FC<SVGProps<SVGSVGElement>>
  export const SquarePlay: FC<SVGProps<SVGSVGElement>>
  export const SquarePlus: FC<SVGProps<SVGSVGElement>>
  export const SquarePower: FC<SVGProps<SVGSVGElement>>
  export const SquareRadical: FC<SVGProps<SVGSVGElement>>
  export const SquareScissors: FC<SVGProps<SVGSVGElement>>
  export const SquareSigma: FC<SVGProps<SVGSVGElement>>
  export const SquareSlash: FC<SVGProps<SVGSVGElement>>
  export const SquareSplitHorizontal: FC<SVGProps<SVGSVGElement>>
  export const SquareSplitVertical: FC<SVGProps<SVGSVGElement>>
  export const SquareSquare: FC<SVGProps<SVGSVGElement>>
  export const SquareStack: FC<SVGProps<SVGSVGElement>>
  export const SquareTerminal: FC<SVGProps<SVGSVGElement>>
  export const SquareUser: FC<SVGProps<SVGSVGElement>>
  export const SquareUserRound: FC<SVGProps<SVGSVGElement>>
  export const SquareX: FC<SVGProps<SVGSVGElement>>
  export const Squircle: FC<SVGProps<SVGSVGElement>>
  export const Squirrel: FC<SVGProps<SVGSVGElement>>
  export const Stamp: FC<SVGProps<SVGSVGElement>>
  export const StarHalf: FC<SVGProps<SVGSVGElement>>
  export const StarOff: FC<SVGProps<SVGSVGElement>>
  export const StepBack: FC<SVGProps<SVGSVGElement>>
  export const StepForward: FC<SVGProps<SVGSVGElement>>
  export const Stethoscope: FC<SVGProps<SVGSVGElement>>
  export const Sticker: FC<SVGProps<SVGSVGElement>>
  export const StickyNote: FC<SVGProps<SVGSVGElement>>
  export const Store: FC<SVGProps<SVGSVGElement>>
  export const StretchHorizontal: FC<SVGProps<SVGSVGElement>>
  export const StretchVertical: FC<SVGProps<SVGSVGElement>>
  export const Strikethrough: FC<SVGProps<SVGSVGElement>>
  export const Subscript: FC<SVGProps<SVGSVGElement>>
  export const SunDim: FC<SVGProps<SVGSVGElement>>
  export const SunMedium: FC<SVGProps<SVGSVGElement>>
  export const SunMoon: FC<SVGProps<SVGSVGElement>>
  export const SunSnow: FC<SVGProps<SVGSVGElement>>
  export const Sunrise: FC<SVGProps<SVGSVGElement>>
  export const Sunset: FC<SVGProps<SVGSVGElement>>
  export const Superscript: FC<SVGProps<SVGSVGElement>>
  export const SwissFranc: FC<SVGProps<SVGSVGElement>>
  export const SwitchCamera: FC<SVGProps<SVGSVGElement>>
  export const Sword: FC<SVGProps<SVGSVGElement>>
  export const Swords: FC<SVGProps<SVGSVGElement>>
  export const Syringe: FC<SVGProps<SVGSVGElement>>
  export const Table: FC<SVGProps<SVGSVGElement>>
  export const Table2: FC<SVGProps<SVGSVGElement>>
  export const TableCellsMerge: FC<SVGProps<SVGSVGElement>>
  export const TableCellsSplit: FC<SVGProps<SVGSVGElement>>
  export const TableColumnsSplit: FC<SVGProps<SVGSVGElement>>
  export const TableOfContents: FC<SVGProps<SVGSVGElement>>
  export const TableProperties: FC<SVGProps<SVGSVGElement>>
  export const TableRowsSplit: FC<SVGProps<SVGSVGElement>>
  export const TabletSmartphone: FC<SVGProps<SVGSVGElement>>
  export const Tablets: FC<SVGProps<SVGSVGElement>>
  export const Tag: FC<SVGProps<SVGSVGElement>>
  export const Tags: FC<SVGProps<SVGSVGElement>>
  export const Tally1: FC<SVGProps<SVGSVGElement>>
  export const Tally2: FC<SVGProps<SVGSVGElement>>
  export const Tally3: FC<SVGProps<SVGSVGElement>>
  export const Tally4: FC<SVGProps<SVGSVGElement>>
  export const Tally5: FC<SVGProps<SVGSVGElement>>
  export const Tangent: FC<SVGProps<SVGSVGElement>>
  export const Target: FC<SVGProps<SVGSVGElement>>
  export const Telescope: FC<SVGProps<SVGSVGElement>>
  export const Tent: FC<SVGProps<SVGSVGElement>>
  export const TentTree: FC<SVGProps<SVGSVGElement>>
  export const Terminal: FC<SVGProps<SVGSVGElement>>
  export const TestTube: FC<SVGProps<SVGSVGElement>>
  export const TestTube2: FC<SVGProps<SVGSVGElement>>
  export const TestTubes: FC<SVGProps<SVGSVGElement>>
  export const Text: FC<SVGProps<SVGSVGElement>>
  export const TextCursor: FC<SVGProps<SVGSVGElement>>
  export const TextCursorInput: FC<SVGProps<SVGSVGElement>>
  export const TextQuote: FC<SVGProps<SVGSVGElement>>
  export const TextSearch: FC<SVGProps<SVGSVGElement>>
  export const TextSelect: FC<SVGProps<SVGSVGElement>>
  export const Theater: FC<SVGProps<SVGSVGElement>>
  export const ThermometerSnowflake: FC<SVGProps<SVGSVGElement>>
  export const ThermometerSun: FC<SVGProps<SVGSVGElement>>
  export const ThumbsDown: FC<SVGProps<SVGSVGElement>>
  export const ThumbsUp: FC<SVGProps<SVGSVGElement>>
  export const Ticket: FC<SVGProps<SVGSVGElement>>
  export const TicketCheck: FC<SVGProps<SVGSVGElement>>
  export const TicketMinus: FC<SVGProps<SVGSVGElement>>
  export const TicketPercent: FC<SVGProps<SVGSVGElement>>
  export const TicketPlus: FC<SVGProps<SVGSVGElement>>
  export const TicketSlash: FC<SVGProps<SVGSVGElement>>
  export const TicketX: FC<SVGProps<SVGSVGElement>>
  export const Timer: FC<SVGProps<SVGSVGElement>>
  export const TimerOff: FC<SVGProps<SVGSVGElement>>
  export const TimerReset: FC<SVGProps<SVGSVGElement>>
  export const ToggleLeft: FC<SVGProps<SVGSVGElement>>
  export const ToggleRight: FC<SVGProps<SVGSVGElement>>
  export const Tornado: FC<SVGProps<SVGSVGElement>>
  export const Touchpad: FC<SVGProps<SVGSVGElement>>
  export const TouchpadOff: FC<SVGProps<SVGSVGElement>>
  export const TowerControl: FC<SVGProps<SVGSVGElement>>
  export const ToyBrick: FC<SVGProps<SVGSVGElement>>
  export const Tractor: FC<SVGProps<SVGSVGElement>>
  export const TrafficCone: FC<SVGProps<SVGSVGElement>>
  export const Train: FC<SVGProps<SVGSVGElement>>
  export const TrainFront: FC<SVGProps<SVGSVGElement>>
  export const TrainFrontTunnel: FC<SVGProps<SVGSVGElement>>
  export const TrainTrack: FC<SVGProps<SVGSVGElement>>
  export const TramFront: FC<SVGProps<SVGSVGElement>>
  export const Trash: FC<SVGProps<SVGSVGElement>>
  export const Trash2: FC<SVGProps<SVGSVGElement>>
  export const TreeDeciduous: FC<SVGProps<SVGSVGElement>>
  export const TreePine: FC<SVGProps<SVGSVGElement>>
  export const Trees: FC<SVGProps<SVGSVGElement>>
  export const Trello: FC<SVGProps<SVGSVGElement>>
  export const TrendingDown: FC<SVGProps<SVGSVGElement>>
  export const TrendingUp: FC<SVGProps<SVGSVGElement>>
  export const TriangleAlert: FC<SVGProps<SVGSVGElement>>
  export const TriangleRight: FC<SVGProps<SVGSVGElement>>
  export const Trophy: FC<SVGProps<SVGSVGElement>>
  export const Truck: FC<SVGProps<SVGSVGElement>>
  export const Turtle: FC<SVGProps<SVGSVGElement>>
  export const Tv: FC<SVGProps<SVGSVGElement>>
  export const Tv2: FC<SVGProps<SVGSVGElement>>
  export const Twitch: FC<SVGProps<SVGSVGElement>>
  export const Twitter: FC<SVGProps<SVGSVGElement>>
  export const Type: FC<SVGProps<SVGSVGElement>>
  export const Umbrella: FC<SVGProps<SVGSVGElement>>
  export const UmbrellaOff: FC<SVGProps<SVGSVGElement>>
  export const Underline: FC<SVGProps<SVGSVGElement>>
  export const Undo: FC<SVGProps<SVGSVGElement>>
  export const Undo2: FC<SVGProps<SVGSVGElement>>
  export const UndoDot: FC<SVGProps<SVGSVGElement>>
  export const UnfoldHorizontal: FC<SVGProps<SVGSVGElement>>
  export const UnfoldVertical: FC<SVGProps<SVGSVGElement>>
  export const Ungroup: FC<SVGProps<SVGSVGElement>>
  export const University: FC<SVGProps<SVGSVGElement>>
  export const Unlink: FC<SVGProps<SVGSVGElement>>
  export const Unlink2: FC<SVGProps<SVGSVGElement>>
  export const Unlock: FC<SVGProps<SVGSVGElement>>
  export const UnlockKeyhole: FC<SVGProps<SVGSVGElement>>
  export const Unplug: FC<SVGProps<SVGSVGElement>>
  export const Upload: FC<SVGProps<SVGSVGElement>>
  export const UploadCloud: FC<SVGProps<SVGSVGElement>>
  export const Usb: FC<SVGProps<SVGSVGElement>>
  export const UserCheck: FC<SVGProps<SVGSVGElement>>
  export const UserCog: FC<SVGProps<SVGSVGElement>>
  export const UserMinus: FC<SVGProps<SVGSVGElement>>
  export const UserPen: FC<SVGProps<SVGSVGElement>>
  export const UserPlus: FC<SVGProps<SVGSVGElement>>
  export const UserRound: FC<SVGProps<SVGSVGElement>>
  export const UserRoundCheck: FC<SVGProps<SVGSVGElement>>
  export const UserRoundCog: FC<SVGProps<SVGSVGElement>>
  export const UserRoundMinus: FC<SVGProps<SVGSVGElement>>
  export const UserRoundPen: FC<SVGProps<SVGSVGElement>>
  export const UserRoundPlus: FC<SVGProps<SVGSVGElement>>
  export const UserRoundSearch: FC<SVGProps<SVGSVGElement>>
  export const UserRoundX: FC<SVGProps<SVGSVGElement>>
  export const UserSearch: FC<SVGProps<SVGSVGElement>>
  export const UserX: FC<SVGProps<SVGSVGElement>>
  export const UsersRound: FC<SVGProps<SVGSVGElement>>
  export const Utensils: FC<SVGProps<SVGSVGElement>>
  export const UtensilsCrossed: FC<SVGProps<SVGSVGElement>>
  export const UtilityPole: FC<SVGProps<SVGSVGElement>>
  export const Variable: FC<SVGProps<SVGSVGElement>>
  export const Vault: FC<SVGProps<SVGSVGElement>>
  export const Vegan: FC<SVGProps<SVGSVGElement>>
  export const VenetianMask: FC<SVGProps<SVGSVGElement>>
  export const Vibrate: FC<SVGProps<SVGSVGElement>>
  export const VibrateOff: FC<SVGProps<SVGSVGElement>>
  export const Video: FC<SVGProps<SVGSVGElement>>
  export const VideoOff: FC<SVGProps<SVGSVGElement>>
  export const Videotape: FC<SVGProps<SVGSVGElement>>
  export const View: FC<SVGProps<SVGSVGElement>>
  export const Voicemail: FC<SVGProps<SVGSVGElement>>
  export const Volume1: FC<SVGProps<SVGSVGElement>>
  export const Volume2: FC<SVGProps<SVGSVGElement>>
  export const VolumeX: FC<SVGProps<SVGSVGElement>>
  export const Vote: FC<SVGProps<SVGSVGElement>>
  export const Wallet: FC<SVGProps<SVGSVGElement>>
  export const Wallet2: FC<SVGProps<SVGSVGElement>>
  export const WalletCards: FC<SVGProps<SVGSVGElement>>
  export const Wallpaper: FC<SVGProps<SVGSVGElement>>
  export const Wand: FC<SVGProps<SVGSVGElement>>
  export const Wand2: FC<SVGProps<SVGSVGElement>>
  export const Warehouse: FC<SVGProps<SVGSVGElement>>
  export const WashingMachine: FC<SVGProps<SVGSVGElement>>
  export const Watch: FC<SVGProps<SVGSVGElement>>
  export const Waves: FC<SVGProps<SVGSVGElement>>
  export const Waypoints: FC<SVGProps<SVGSVGElement>>
  export const Webcam: FC<SVGProps<SVGSVGElement>>
  export const Webhook: FC<SVGProps<SVGSVGElement>>
  export const Weight: FC<SVGProps<SVGSVGElement>>
  export const Wheat: FC<SVGProps<SVGSVGElement>>
  export const WheatOff: FC<SVGProps<SVGSVGElement>>
  export const WholeWord: FC<SVGProps<SVGSVGElement>>
  export const Wifi: FC<SVGProps<SVGSVGElement>>
  export const WifiOff: FC<SVGProps<SVGSVGElement>>
  export const Wind: FC<SVGProps<SVGSVGElement>>
  export const Wine: FC<SVGProps<SVGSVGElement>>
  export const WineOff: FC<SVGProps<SVGSVGElement>>
  export const Workflow: FC<SVGProps<SVGSVGElement>>
  export const Worm: FC<SVGProps<SVGSVGElement>>
  export const WrapText: FC<SVGProps<SVGSVGElement>>
  export const Wrench: FC<SVGProps<SVGSVGElement>>
  export const X: FC<SVGProps<SVGSVGElement>>
  export const XCircle: FC<SVGProps<SVGSVGElement>>
  export const XOctagon: FC<SVGProps<SVGSVGElement>>
  export const XSquare: FC<SVGProps<SVGSVGElement>>
  export const Youtube: FC<SVGProps<SVGSVGElement>>
  export const ZapOff: FC<SVGProps<SVGSVGElement>>
  export const ZoomIn: FC<SVGProps<SVGSVGElement>>
  export const ZoomOut: FC<SVGProps<SVGSVGElement>>
  export const Building2: FC<SVGProps<SVGSVGElement>>
  export const Factory: FC<SVGProps<SVGSVGElement>>
  export const Banknote: FC<SVGProps<SVGSVGElement>>
  export const Calculator: FC<SVGProps<SVGSVGElement>>
  export const CalendarDays: FC<SVGProps<SVGSVGElement>>
  export const CalendarRange: FC<SVGProps<SVGSVGElement>>
  export const Car: FC<SVGProps<SVGSVGElement>>
  export const CarTaxiFront: FC<SVGProps<SVGSVGElement>>
  export const CircuitBoard: FC<SVGProps<SVGSVGElement>>
  export const Cog: FC<SVGProps<SVGSVGElement>>
  export const Compass: FC<SVGProps<SVGSVGElement>>
  export const Component: FC<SVGProps<SVGSVGElement>>
  export const Construction: FC<SVGProps<SVGSVGElement>>
  export const Container: FC<SVGProps<SVGSVGElement>>
  export const FileBarChart: FC<SVGProps<SVGSVGElement>>
  export const FileBarChart2: FC<SVGProps<SVGSVGElement>>
  export const FileBox: FC<SVGProps<SVGSVGElement>>
  export const FileDigit: FC<SVGProps<SVGSVGElement>>
  export const FileSpreadsheet: FC<SVGProps<SVGSVGElement>>
  export const Globe2: FC<SVGProps<SVGSVGElement>>
  export const HandCoins: FC<SVGProps<SVGSVGElement>>
  export const HandHeart: FC<SVGProps<SVGSVGElement>>
  export const Handshake: FC<SVGProps<SVGSVGElement>>
  export const HeartHandshake: FC<SVGProps<SVGSVGElement>>
  export const Hospital: FC<SVGProps<SVGSVGElement>>
  export const LandPlot: FC<SVGProps<SVGSVGElement>>
  export const LineChart: FC<SVGProps<SVGSVGElement>>
  export const LucideIcon: FC<SVGProps<SVGSVGElement>>
  export const MailOpen: FC<SVGProps<SVGSVGElement>>
  export const MailQuestion: FC<SVGProps<SVGSVGElement>>
  export const MailSearch: FC<SVGProps<SVGSVGElement>>
  export const MailWarning: FC<SVGProps<SVGSVGElement>>
  export const MailX: FC<SVGProps<SVGSVGElement>>
  export const Map: FC<SVGProps<SVGSVGElement>>
  export const Network: FC<SVGProps<SVGSVGElement>>
  export const Newspaper: FC<SVGProps<SVGSVGElement>>
  export const Package2: FC<SVGProps<SVGSVGElement>>
  export const PackageSearch: FC<SVGProps<SVGSVGElement>>
  export const PackageX: FC<SVGProps<SVGSVGElement>>
  export const PanelLeft: FC<SVGProps<SVGSVGElement>>
  export const PanelRight: FC<SVGProps<SVGSVGElement>>
  export const PhoneCall: FC<SVGProps<SVGSVGElement>>
  export const PhoneForwarded: FC<SVGProps<SVGSVGElement>>
  export const PhoneIncoming: FC<SVGProps<SVGSVGElement>>
  export const PhoneMissed: FC<SVGProps<SVGSVGElement>>
  export const PhoneOutgoing: FC<SVGProps<SVGSVGElement>>
  export const PieChart: FC<SVGProps<SVGSVGElement>>
  export const PiggyBank: FC<SVGProps<SVGSVGElement>>
  export const Plane: FC<SVGProps<SVGSVGElement>>
  export const Presentation: FC<SVGProps<SVGSVGElement>>
  export const Printer: FC<SVGProps<SVGSVGElement>>
  export const QrCode: FC<SVGProps<SVGSVGElement>>
  export const Receipt: FC<SVGProps<SVGSVGElement>>
  export const Scan: FC<SVGProps<SVGSVGElement>>
  export const ScanBarcode: FC<SVGProps<SVGSVGElement>>
  export const ScanEye: FC<SVGProps<SVGSVGElement>>
  export const ScanFace: FC<SVGProps<SVGSVGElement>>
  export const ScanLine: FC<SVGProps<SVGSVGElement>>
  export const ScanSearch: FC<SVGProps<SVGSVGElement>>
  export const ScanText: FC<SVGProps<SVGSVGElement>>
  export const School: FC<SVGProps<SVGSVGElement>>
  export const SearchCode: FC<SVGProps<SVGSVGElement>>
  export const SearchSlash: FC<SVGProps<SVGSVGElement>>
  export const SearchX: FC<SVGProps<SVGSVGElement>>
  export const SendHorizontal: FC<SVGProps<SVGSVGElement>>
  export const Settings2: FC<SVGProps<SVGSVGElement>>
  export const ShieldAlert: FC<SVGProps<SVGSVGElement>>
  export const ShieldBan: FC<SVGProps<SVGSVGElement>>
  export const ShieldCheck: FC<SVGProps<SVGSVGElement>>
  export const ShieldEllipsis: FC<SVGProps<SVGSVGElement>>
  export const ShieldHalf: FC<SVGProps<SVGSVGElement>>
  export const ShieldMinus: FC<SVGProps<SVGSVGElement>>
  export const ShieldOff: FC<SVGProps<SVGSVGElement>>
  export const ShieldPlus: FC<SVGProps<SVGSVGElement>>
  export const ShieldQuestion: FC<SVGProps<SVGSVGElement>>
  export const ShieldX: FC<SVGProps<SVGSVGElement>>
  export const ShoppingBag: FC<SVGProps<SVGSVGElement>>
  export const ShoppingBasket: FC<SVGProps<SVGSVGElement>>
  export const ShoppingCart: FC<SVGProps<SVGSVGElement>>
  export const Shovel: FC<SVGProps<SVGSVGElement>>
  export const Signal: FC<SVGProps<SVGSVGElement>>
  export const SignalHigh: FC<SVGProps<SVGSVGElement>>
  export const SignalLow: FC<SVGProps<SVGSVGElement>>
  export const SignalMedium: FC<SVGProps<SVGSVGElement>>
  export const SignalZero: FC<SVGProps<SVGSVGElement>>
  export const Siren: FC<SVGProps<SVGSVGElement>>
  export const SquareActivity: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowDown: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowDownLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowDownRight: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowOutDownLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowOutDownRight: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowOutUpLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowOutUpRight: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowRight: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowUp: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowUpLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowUpRight: FC<SVGProps<SVGSVGElement>>
  export const SquareAsterisk: FC<SVGProps<SVGSVGElement>>
  export const SquareBottomDashedScissors: FC<SVGProps<SVGSVGElement>>
  export const SquareChartGantt: FC<SVGProps<SVGSVGElement>>
  export const SquareCheck: FC<SVGProps<SVGSVGElement>>
  export const SquareCheckBig: FC<SVGProps<SVGSVGElement>>
  export const SquareChevronDown: FC<SVGProps<SVGSVGElement>>
  export const SquareChevronLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareChevronRight: FC<SVGProps<SVGSVGElement>>
  export const SquareChevronUp: FC<SVGProps<SVGSVGElement>>
  export const SquareCode: FC<SVGProps<SVGSVGElement>>
  export const SquareDashed: FC<SVGProps<SVGSVGElement>>
  export const SquareDashedBottomCode: FC<SVGProps<SVGSVGElement>>
  export const SquareDashedBottom: FC<SVGProps<SVGSVGElement>>
  export const SquareDashedKanban: FC<SVGProps<SVGSVGElement>>
  export const SquareDashedMousePointer: FC<SVGProps<SVGSVGElement>>
  export const SquareDivide: FC<SVGProps<SVGSVGElement>>
  export const SquareDot: FC<SVGProps<SVGSVGElement>>
  export const SquareEqual: FC<SVGProps<SVGSVGElement>>
  export const SquareFunction: FC<SVGProps<SVGSVGElement>>
  export const SquareKanban: FC<SVGProps<SVGSVGElement>>
  export const SquareLibrary: FC<SVGProps<SVGSVGElement>>
  export const SquareM: FC<SVGProps<SVGSVGElement>>
  export const SquareMenu: FC<SVGProps<SVGSVGElement>>
  export const SquareMinus: FC<SVGProps<SVGSVGElement>>
  export const SquareMousePointer: FC<SVGProps<SVGSVGElement>>
  export const SquareParking: FC<SVGProps<SVGSVGElement>>
  export const SquareParkingOff: FC<SVGProps<SVGSVGElement>>
  export const SquarePen: FC<SVGProps<SVGSVGElement>>
  export const SquarePercent: FC<SVGProps<SVGSVGElement>>
  export const SquarePi: FC<SVGProps<SVGSVGElement>>
  export const SquarePilcrow: FC<SVGProps<SVGSVGElement>>
  export const SquarePlay: FC<SVGProps<SVGSVGElement>>
  export const SquarePlus: FC<SVGProps<SVGSVGElement>>
  export const SquarePower: FC<SVGProps<SVGSVGElement>>
  export const SquareRadical: FC<SVGProps<SVGSVGElement>>
  export const SquareScissors: FC<SVGProps<SVGSVGElement>>
  export const SquareSigma: FC<SVGProps<SVGSVGElement>>
  export const SquareSlash: FC<SVGProps<SVGSVGElement>>
  export const SquareSplitHorizontal: FC<SVGProps<SVGSVGElement>>
  export const SquareSplitVertical: FC<SVGProps<SVGSVGElement>>
  export const SquareSquare: FC<SVGProps<SVGSVGElement>>
  export const SquareStack: FC<SVGProps<SVGSVGElement>>
  export const SquareTerminal: FC<SVGProps<SVGSVGElement>>
  export const SquareUser: FC<SVGProps<SVGSVGElement>>
  export const SquareUserRound: FC<SVGProps<SVGSVGElement>>
  export const SquareX: FC<SVGProps<SVGSVGElement>>
  export const StarHalf: FC<SVGProps<SVGSVGElement>>
  export const StarOff: FC<SVGProps<SVGSVGElement>>
  export const Store: FC<SVGProps<SVGSVGElement>>
  export const SunMedium: FC<SVGProps<SVGSVGElement>>
  export const SunMoon: FC<SVGProps<SVGSVGElement>>
  export const Sunrise: FC<SVGProps<SVGSVGElement>>
  export const Sunset: FC<SVGProps<SVGSVGElement>>
  export const Sword: FC<SVGProps<SVGSVGElement>>
  export const Swords: FC<SVGProps<SVGSVGElement>>
  export const Syringe: FC<SVGProps<SVGSVGElement>>
  export const Table: FC<SVGProps<SVGSVGElement>>
  export const Table2: FC<SVGProps<SVGSVGElement>>
  export const TableCellsMerge: FC<SVGProps<SVGSVGElement>>
  export const TableCellsSplit: FC<SVGProps<SVGSVGElement>>
  export const TableColumnsSplit: FC<SVGProps<SVGSVGElement>>
  export const TableOfContents: FC<SVGProps<SVGSVGElement>>
  export const TableProperties: FC<SVGProps<SVGSVGElement>>
  export const TableRowsSplit: FC<SVGProps<SVGSVGElement>>
  export const TabletSmartphone: FC<SVGProps<SVGSVGElement>>
  export const Tablets: FC<SVGProps<SVGSVGElement>>
  export const Tag: FC<SVGProps<SVGSVGElement>>
  export const Tags: FC<SVGProps<SVGSVGElement>>
  export const Target: FC<SVGProps<SVGSVGElement>>
  export const Tent: FC<SVGProps<SVGSVGElement>>
  export const TentTree: FC<SVGProps<SVGSVGElement>>
  export const Terminal: FC<SVGProps<SVGSVGElement>>
  export const TestTube: FC<SVGProps<SVGSVGElement>>
  export const TestTube2: FC<SVGProps<SVGSVGElement>>
  export const TestTubes: FC<SVGProps<SVGSVGElement>>
  export const Text: FC<SVGProps<SVGSVGElement>>
  export const TextCursor: FC<SVGProps<SVGSVGElement>>
  export const TextCursorInput: FC<SVGProps<SVGSVGElement>>
  export const TextQuote: FC<SVGProps<SVGSVGElement>>
  export const TextSearch: FC<SVGProps<SVGSVGElement>>
  export const TextSelect: FC<SVGProps<SVGSVGElement>>
  export const Theater: FC<SVGProps<SVGSVGElement>>
  export const ThermometerSnowflake: FC<SVGProps<SVGSVGElement>>
  export const ThermometerSun: FC<SVGProps<SVGSVGElement>>
  export const Ticket: FC<SVGProps<SVGSVGElement>>
  export const TicketCheck: FC<SVGProps<SVGSVGElement>>
  export const TicketMinus: FC<SVGProps<SVGSVGElement>>
  export const TicketPercent: FC<SVGProps<SVGSVGElement>>
  export const TicketPlus: FC<SVGProps<SVGSVGElement>>
  export const TicketSlash: FC<SVGProps<SVGSVGElement>>
  export const TicketX: FC<SVGProps<SVGSVGElement>>
  export const Timer: FC<SVGProps<SVGSVGElement>>
  export const TimerOff: FC<SVGProps<SVGSVGElement>>
  export const TimerReset: FC<SVGProps<SVGSVGElement>>
  export const ToggleLeft: FC<SVGProps<SVGSVGElement>>
  export const ToggleRight: FC<SVGProps<SVGSVGElement>>
  export const Tornado: FC<SVGProps<SVGSVGElement>>
  export const Touchpad: FC<SVGProps<SVGSVGElement>>
  export const TouchpadOff: FC<SVGProps<SVGSVGElement>>
  export const TowerControl: FC<SVGProps<SVGSVGElement>>
  export const ToyBrick: FC<SVGProps<SVGSVGElement>>
  export const Tractor: FC<SVGProps<SVGSVGElement>>
  export const TrafficCone: FC<SVGProps<SVGSVGElement>>
  export const Train: FC<SVGProps<SVGSVGElement>>
  export const TrainFront: FC<SVGProps<SVGSVGElement>>
  export const TrainFrontTunnel: FC<SVGProps<SVGSVGElement>>
  export const TrainTrack: FC<SVGProps<SVGSVGElement>>
  export const TramFront: FC<SVGProps<SVGSVGElement>>
  export const TreeDeciduous: FC<SVGProps<SVGSVGElement>>
  export const TreePine: FC<SVGProps<SVGSVGElement>>
  export const Trees: FC<SVGProps<SVGSVGElement>>
  export const TrendingDown: FC<SVGProps<SVGSVGElement>>
  export const TrendingUp: FC<SVGProps<SVGSVGElement>>
  export const TriangleAlert: FC<SVGProps<SVGSVGElement>>
  export const TriangleRight: FC<SVGProps<SVGSVGElement>>
  export const Trophy: FC<SVGProps<SVGSVGElement>>
  export const Truck: FC<SVGProps<SVGSVGElement>>
  export const Turtle: FC<SVGProps<SVGSVGElement>>
  export const Tv: FC<SVGProps<SVGSVGElement>>
  export const Tv2: FC<SVGProps<SVGSVGElement>>
  export const Type: FC<SVGProps<SVGSVGElement>>
  export const Umbrella: FC<SVGProps<SVGSVGElement>>
  export const UmbrellaOff: FC<SVGProps<SVGSVGElement>>
  export const Underline: FC<SVGProps<SVGSVGElement>>
  export const Undo: FC<SVGProps<SVGSVGElement>>
  export const Undo2: FC<SVGProps<SVGSVGElement>>
  export const UndoDot: FC<SVGProps<SVGSVGElement>>
  export const UnfoldHorizontal: FC<SVGProps<SVGSVGElement>>
  export const UnfoldVertical: FC<SVGProps<SVGSVGElement>>
  export const Ungroup: FC<SVGProps<SVGSVGElement>>
  export const University: FC<SVGProps<SVGSVGElement>>
  export const Unlink: FC<SVGProps<SVGSVGElement>>
  export const Unlink2: FC<SVGProps<SVGSVGElement>>
  export const Unlock: FC<SVGProps<SVGSVGElement>>
  export const UnlockKeyhole: FC<SVGProps<SVGSVGElement>>
  export const Unplug: FC<SVGProps<SVGSVGElement>>
  export const Upload: FC<SVGProps<SVGSVGElement>>
  export const UploadCloud: FC<SVGProps<SVGSVGElement>>
  export const Usb: FC<SVGProps<SVGSVGElement>>
  export const UserCheck: FC<SVGProps<SVGSVGElement>>
  export const UserCog: FC<SVGProps<SVGSVGElement>>
  export const UserMinus: FC<SVGProps<SVGSVGElement>>
  export const UserPen: FC<SVGProps<SVGSVGElement>>
  export const UserPlus: FC<SVGProps<SVGSVGElement>>
  export const UserRound: FC<SVGProps<SVGSVGElement>>
  export const UserRoundCheck: FC<SVGProps<SVGSVGElement>>
  export const UserRoundCog: FC<SVGProps<SVGSVGElement>>
  export const UserRoundMinus: FC<SVGProps<SVGSVGElement>>
  export const UserRoundPen: FC<SVGProps<SVGSVGElement>>
  export const UserRoundPlus: FC<SVGProps<SVGSVGElement>>
  export const UserRoundSearch: FC<SVGProps<SVGSVGElement>>
  export const UserRoundX: FC<SVGProps<SVGSVGElement>>
  export const UserSearch: FC<SVGProps<SVGSVGElement>>
  export const UserX: FC<SVGProps<SVGSVGElement>>
  export const UsersRound: FC<SVGProps<SVGSVGElement>>
  export const Utensils: FC<SVGProps<SVGSVGElement>>
  export const UtensilsCrossed: FC<SVGProps<SVGSVGElement>>
  export const Variable: FC<SVGProps<SVGSVGElement>>
  export const Vault: FC<SVGProps<SVGSVGElement>>
  export const Vegan: FC<SVGProps<SVGSVGElement>>
  export const VenetianMask: FC<SVGProps<SVGSVGElement>>
  export const Vibrate: FC<SVGProps<SVGSVGElement>>
  export const VibrateOff: FC<SVGProps<SVGSVGElement>>
  export const Video: FC<SVGProps<SVGSVGElement>>
  export const VideoOff: FC<SVGProps<SVGSVGElement>>
  export const Videotape: FC<SVGProps<SVGSVGElement>>
  export const View: FC<SVGProps<SVGSVGElement>>
  export const Voicemail: FC<SVGProps<SVGSVGElement>>
  export const Volume1: FC<SVGProps<SVGSVGElement>>
  export const Volume2: FC<SVGProps<SVGSVGElement>>
  export const VolumeX: FC<SVGProps<SVGSVGElement>>
  export const Vote: FC<SVGProps<SVGSVGElement>>
  export const Wallet: FC<SVGProps<SVGSVGElement>>
  export const Wallet2: FC<SVGProps<SVGSVGElement>>
  export const WalletCards: FC<SVGProps<SVGSVGElement>>
  export const Wallpaper: FC<SVGProps<SVGSVGElement>>
  export const Wand: FC<SVGProps<SVGSVGElement>>
  export const Wand2: FC<SVGProps<SVGSVGElement>>
  export const Warehouse: FC<SVGProps<SVGSVGElement>>
  export const WashingMachine: FC<SVGProps<SVGSVGElement>>
  export const Watch: FC<SVGProps<SVGSVGElement>>
  export const Waves: FC<SVGProps<SVGSVGElement>>
  export const Waypoints: FC<SVGProps<SVGSVGElement>>
  export const Webcam: FC<SVGProps<SVGSVGElement>>
  export const Webhook: FC<SVGProps<SVGSVGElement>>
  export const Weight: FC<SVGProps<SVGSVGElement>>
  export const Wheat: FC<SVGProps<SVGSVGElement>>
  export const WheatOff: FC<SVGProps<SVGSVGElement>>
  export const WholeWord: FC<SVGProps<SVGSVGElement>>
  export const Wifi: FC<SVGProps<SVGSVGElement>>
  export const WifiOff: FC<SVGProps<SVGSVGElement>>
  export const Wind: FC<SVGProps<SVGSVGElement>>
  export const Wine: FC<SVGProps<SVGSVGElement>>
  export const WineOff: FC<SVGProps<SVGSVGElement>>
  export const Workflow: FC<SVGProps<SVGSVGElement>>
  export const Worm: FC<SVGProps<SVGSVGElement>>
  export const WrapText: FC<SVGProps<SVGSVGElement>>
  export const Wrench: FC<SVGProps<SVGSVGElement>>
  export const X: FC<SVGProps<SVGSVGElement>>
  export const XCircle: FC<SVGProps<SVGSVGElement>>
  export const XOctagon: FC<SVGProps<SVGSVGElement>>
  export const XSquare: FC<SVGProps<SVGSVGElement>>
  export const Youtube: FC<SVGProps<SVGSVGElement>>
  export const ZapOff: FC<SVGProps<SVGSVGElement>>
  export const ZoomIn: FC<SVGProps<SVGSVGElement>>
  export const ZoomOut: FC<SVGProps<SVGSVGElement>>
  export const Building2: FC<SVGProps<SVGSVGElement>>
  export const Factory: FC<SVGProps<SVGSVGElement>>
  export const Banknote: FC<SVGProps<SVGSVGElement>>
  export const Calculator: FC<SVGProps<SVGSVGElement>>
  export const CalendarDays: FC<SVGProps<SVGSVGElement>>
  export const CalendarRange: FC<SVGProps<SVGSVGElement>>
  export const Car: FC<SVGProps<SVGSVGElement>>
  export const CarTaxiFront: FC<SVGProps<SVGSVGElement>>
  export const CircuitBoard: FC<SVGProps<SVGSVGElement>>
  export const Cog: FC<SVGProps<SVGSVGElement>>
  export const Compass: FC<SVGProps<SVGSVGElement>>
  export const Component: FC<SVGProps<SVGSVGElement>>
  export const Construction: FC<SVGProps<SVGSVGElement>>
  export const Container: FC<SVGProps<SVGSVGElement>>
  export const FileBarChart: FC<SVGProps<SVGSVGElement>>
  export const FileBarChart2: FC<SVGProps<SVGSVGElement>>
  export const FileBox: FC<SVGProps<SVGSVGElement>>
  export const FileDigit: FC<SVGProps<SVGSVGElement>>
  export const FileSpreadsheet: FC<SVGProps<SVGSVGElement>>
  export const Globe2: FC<SVGProps<SVGSVGElement>>
  export const HandCoins: FC<SVGProps<SVGSVGElement>>
  export const HandHeart: FC<SVGProps<SVGSVGElement>>
  export const Handshake: FC<SVGProps<SVGSVGElement>>
  export const HeartHandshake: FC<SVGProps<SVGSVGElement>>
  export const Hospital: FC<SVGProps<SVGSVGElement>>
  export const LandPlot: FC<SVGProps<SVGSVGElement>>
  export const LineChart: FC<SVGProps<SVGSVGElement>>
  export const LucideIcon: FC<SVGProps<SVGSVGElement>>
  export const MailOpen: FC<SVGProps<SVGSVGElement>>
  export const MailQuestion: FC<SVGProps<SVGSVGElement>>
  export const MailSearch: FC<SVGProps<SVGSVGElement>>
  export const MailWarning: FC<SVGProps<SVGSVGElement>>
  export const MailX: FC<SVGProps<SVGSVGElement>>
  export const Map: FC<SVGProps<SVGSVGElement>>
  export const Network: FC<SVGProps<SVGSVGElement>>
  export const Newspaper: FC<SVGProps<SVGSVGElement>>
  export const Package2: FC<SVGProps<SVGSVGElement>>
  export const PackageSearch: FC<SVGProps<SVGSVGElement>>
  export const PackageX: FC<SVGProps<SVGSVGElement>>
  export const PanelLeft: FC<SVGProps<SVGSVGElement>>
  export const PanelRight: FC<SVGProps<SVGSVGElement>>
  export const PhoneCall: FC<SVGProps<SVGSVGElement>>
  export const PhoneForwarded: FC<SVGProps<SVGSVGElement>>
  export const PhoneIncoming: FC<SVGProps<SVGSVGElement>>
  export const PhoneMissed: FC<SVGProps<SVGSVGElement>>
  export const PhoneOutgoing: FC<SVGProps<SVGSVGElement>>
  export const PieChart: FC<SVGProps<SVGSVGElement>>
  export const PiggyBank: FC<SVGProps<SVGSVGElement>>
  export const Plane: FC<SVGProps<SVGSVGElement>>
  export const Presentation: FC<SVGProps<SVGSVGElement>>
  export const Printer: FC<SVGProps<SVGSVGElement>>
  export const QrCode: FC<SVGProps<SVGSVGElement>>
  export const Receipt: FC<SVGProps<SVGSVGElement>>
  export const Scan: FC<SVGProps<SVGSVGElement>>
  export const ScanBarcode: FC<SVGProps<SVGSVGElement>>
  export const ScanEye: FC<SVGProps<SVGSVGElement>>
  export const ScanFace: FC<SVGProps<SVGSVGElement>>
  export const ScanLine: FC<SVGProps<SVGSVGElement>>
  export const ScanSearch: FC<SVGProps<SVGSVGElement>>
  export const ScanText: FC<SVGProps<SVGSVGElement>>
  export const School: FC<SVGProps<SVGSVGElement>>
  export const SearchCode: FC<SVGProps<SVGSVGElement>>
  export const SearchSlash: FC<SVGProps<SVGSVGElement>>
  export const SearchX: FC<SVGProps<SVGSVGElement>>
  export const SendHorizontal: FC<SVGProps<SVGSVGElement>>
  export const Settings2: FC<SVGProps<SVGSVGElement>>
  export const ShieldAlert: FC<SVGProps<SVGSVGElement>>
  export const ShieldBan: FC<SVGProps<SVGSVGElement>>
  export const ShieldCheck: FC<SVGProps<SVGSVGElement>>
  export const ShieldEllipsis: FC<SVGProps<SVGSVGElement>>
  export const ShieldHalf: FC<SVGProps<SVGSVGElement>>
  export const ShieldMinus: FC<SVGProps<SVGSVGElement>>
  export const ShieldOff: FC<SVGProps<SVGSVGElement>>
  export const ShieldPlus: FC<SVGProps<SVGSVGElement>>
  export const ShieldQuestion: FC<SVGProps<SVGSVGElement>>
  export const ShieldX: FC<SVGProps<SVGSVGElement>>
  export const ShoppingBag: FC<SVGProps<SVGSVGElement>>
  export const ShoppingBasket: FC<SVGProps<SVGSVGElement>>
  export const ShoppingCart: FC<SVGProps<SVGSVGElement>>
  export const Shovel: FC<SVGProps<SVGSVGElement>>
  export const Signal: FC<SVGProps<SVGSVGElement>>
  export const SignalHigh: FC<SVGProps<SVGSVGElement>>
  export const SignalLow: FC<SVGProps<SVGSVGElement>>
  export const SignalMedium: FC<SVGProps<SVGSVGElement>>
  export const SignalZero: FC<SVGProps<SVGSVGElement>>
  export const Siren: FC<SVGProps<SVGSVGElement>>
  export const SquareActivity: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowDown: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowDownLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowDownRight: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowOutDownLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowOutDownRight: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowOutUpLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowOutUpRight: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowRight: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowUp: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowUpLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareArrowUpRight: FC<SVGProps<SVGSVGElement>>
  export const SquareAsterisk: FC<SVGProps<SVGSVGElement>>
  export const SquareBottomDashedScissors: FC<SVGProps<SVGSVGElement>>
  export const SquareChartGantt: FC<SVGProps<SVGSVGElement>>
  export const SquareCheck: FC<SVGProps<SVGSVGElement>>
  export const SquareCheckBig: FC<SVGProps<SVGSVGElement>>
  export const SquareChevronDown: FC<SVGProps<SVGSVGElement>>
  export const SquareChevronLeft: FC<SVGProps<SVGSVGElement>>
  export const SquareChevronRight: FC<SVGProps<SVGSVGElement>>
  export const SquareChevronUp: FC<SVGProps<SVGSVGElement>>
  export const SquareCode: FC<SVGProps<SVGSVGElement>>
  export const SquareDashed: FC<SVGProps<SVGSVGElement>>
  export const SquareDashedBottomCode: FC<SVGProps<SVGSVGElement>>
  export const SquareDashedBottom: FC<SVGProps<SVGSVGElement>>
  export const SquareDashedKanban: FC<SVGProps<SVGSVGElement>>
  export const SquareDashedMousePointer: FC<SVGProps<SVGSVGElement>>
  export const SquareDivide: FC<SVGProps<SVGSVGElement>>
  export const SquareDot: FC<SVGProps<SVGSVGElement>>
  export const SquareEqual: FC<SVGProps<SVGSVGElement>>
  export const SquareFunction: FC<SVGProps<SVGSVGElement>>
  export const SquareKanban: FC<SVGProps<SVGSVGElement>>
  export const SquareLibrary: FC<SVGProps<SVGSVGElement>>
  export const SquareM: FC<SVGProps<SVGSVGElement>>
  export const SquareMenu: FC<SVGProps<SVGSVGElement>>
  export const SquareMinus: FC<SVGProps<SVGSVGElement>>
  export const SquareMousePointer: FC<SVGProps<SVGSVGElement>>
  export const SquareParking: FC<SVGProps<SVGSVGElement>>
  export const SquareParkingOff: FC<SVGProps<SVGSVGElement>>
  export const SquarePen: FC<SVGProps<SVGSVGElement>>
  export const SquarePercent: FC<SVGProps<SVGSVGElement>>
  export const SquarePi: FC<SVGProps<SVGSVGElement>>
  export const SquarePilcrow: FC<SVGProps<SVGSVGElement>>
  export const SquarePlay: FC<SVGProps<SVGSVGElement>>
  export const SquarePlus: FC<SVGProps<SVGSVGElement>>
  export const SquarePower: FC<SVGProps<SVGSVGElement>>
  export const SquareRadical: FC<SVGProps<SVGSVGElement>>
  export const SquareScissors: FC<SVGProps<SVGSVGElement>>
  export const SquareSigma: FC<SVGProps<SVGSVGElement>>
  export const SquareSlash: FC<SVGProps<SVGSVGElement>>
  export const SquareSplitHorizontal: FC<SVGProps<SVGSVGElement>>
  export const SquareSplitVertical: FC<SVGProps<SVGSVGElement>>
  export const SquareSquare: FC<SVGProps<SVGSVGElement>>
  export const SquareStack: FC<SVGProps<SVGSVGElement>>
  export const SquareTerminal: FC<SVGProps<SVGSVGElement>>
  export const SquareUser: FC<SVGProps<SVGSVGElement>>
  export const SquareUserRound: FC<SVGProps<SVGSVGElement>>
  export const SquareX: FC<SVGProps<SVGSVGElement>>
  export const StarHalf: FC<SVGProps<SVGSVGElement>>
  export const StarOff: FC<SVGProps<SVGSVGElement>>
  export const Store: FC<SVGProps<SVGSVGElement>>
  export const SunMedium: FC<SVGProps<SVGSVGElement>>
  export const SunMoon: FC<SVGProps<SVGSVGElement>>
  export const Sunrise: FC<SVGProps<SVGSVGElement>>
  export const Sunset: FC<SVGProps<SVGSVGElement>>
  export const Sword: FC<SVGProps<SVGSVGElement>>
  export const Swords: FC<SVGProps<SVGSVGElement>>
  export const Syringe: FC<SVGProps<SVGSVGElement>>
  export const Table: FC<SVGProps<SVGSVGElement>>
  export const Table2: FC<SVGProps<SVGSVGElement>>
  export const TableCellsMerge: FC<SVGProps<SVGSVGElement>>
  export const TableCellsSplit: FC<SVGProps<SVGSVGElement>>
  export const TableColumnsSplit: FC<SVGProps<SVGSVGElement>>
  export const TableOfContents: FC<SVGProps<SVGSVGElement>>
  export const TableProperties: FC<SVGProps<SVGSVGElement>>
  export const TableRowsSplit: FC<SVGProps<SVGSVGElement>>
  export const TabletSmartphone: FC<SVGProps<SVGSVGElement>>
  export const Tablets: FC<SVGProps<SVGSVGElement>>
  export const Tag: FC<SVGProps<SVGSVGElement>>
  export const Tags: FC<SVGProps<SVGSVGElement>>
  export const Target: FC<SVGProps<SVGSVGElement>>
  export const Tent: FC<SVGProps<SVGSVGElement>>
  export const TentTree: FC<SVGProps<SVGSVGElement>>
  export const Terminal: FC<SVGProps<SVGSVGElement>>
  export const TestTube: FC<SVGProps<SVGSVGElement>>
  export const TestTube2: FC<SVGProps<SVGSVGElement>>
  export const TestTubes: FC<SVGProps<SVGSVGElement>>
  export const Text: FC<SVGProps<SVGSVGElement>>
  export const TextCursor: FC<SVGProps<SVGSVGElement>>
  export const TextCursorInput: FC<SVGProps<SVGSVGElement>>
  export const TextQuote: FC<SVGProps<SVGSVGElement>>
  export const TextSearch: FC<SVGProps<SVGSVGElement>>
  export const TextSelect: FC<SVGProps<SVGSVGElement>>
  export const Theater: FC<SVGProps<SVGSVGElement>>
  export const ThermometerSnowflake: FC<SVGProps<SVGSVGElement>>
  export const ThermometerSun: FC<SVGProps<SVGSVGElement>>
  export const Ticket: FC<SVGProps<SVGSVGElement>>
  export const TicketCheck: FC<SVGProps<SVGSVGElement>>
  export const TicketMinus: FC<SVGProps<SVGSVGElement>>
  export const TicketPercent: FC<SVGProps<SVGSVGElement>>
  export const TicketPlus: FC<SVGProps<SVGSVGElement>>
  export const TicketSlash: FC<SVGProps<SVGSVGElement>>
  export const TicketX: FC<SVGProps<SVGSVGElement>>
  export const Timer: FC<SVGProps<SVGSVGElement>>
  export const TimerOff: FC<SVGProps<SVGSVGElement>>
  export const TimerReset: FC<SVGProps<SVGSVGElement>>
  export const ToggleLeft: FC<SVGProps<SVGSVGElement>>
  export const ToggleRight: FC<SVGProps<SVGSVGElement>>
  export const Tornado: FC<SVGProps<SVGSVGElement>>
  export const Touchpad: FC<SVGProps<SVGSVGElement>>
  export const TouchpadOff: FC<SVGProps<SVGSVGElement>>
  export const TowerControl: FC<SVGProps<SVGSVGElement>>
  export const ToyBrick: FC<SVGProps<SVGSVGElement>>
  export const Tractor: FC<SVGProps<SVGSVGElement>>
  export const TrafficCone: FC<SVGProps<SVGSVGElement>>
  export const Train: FC<SVGProps<SVGSVGElement>>
  export const TrainFront: FC<SVGProps<SVGSVGElement>>
  export const TrainFrontTunnel: FC<SVGProps<SVGSVGElement>>
  export const TrainTrack: FC<SVGProps<SVGSVGElement>>
  export const TramFront: FC<SVGProps<SVGSVGElement>>
  export const TreeDeciduous: FC<SVGProps<SVGSVGElement>>
  export const TreePine: FC<SVGProps<SVGSVGElement>>
  export const Trees: FC<SVGProps<SVGSVGElement>>
  export const TrendingDown: FC<SVGProps<SVGSVGElement>>
  export const TrendingUp: FC<SVGProps<SVGSVGElement>>
  export const TriangleAlert: FC<SVGProps<SVGSVGElement>>
  export const TriangleRight: FC<SVGProps<SVGSVGElement>>
  export const Trophy: FC<SVGProps<SVGSVGElement>>
  export const Truck: FC<SVGProps<SVGSVGElement>>
  export const Turtle: FC<SVGProps<SVGSVGElement>>
  export const Tv: FC<SVGProps<SVGSVGElement>>
  export const Tv2: FC<SVGProps<SVGSVGElement>>
  export const Type: FC<SVGProps<SVGSVGElement>>
  export const Umbrella: FC<SVGProps<SVGSVGElement>>
  export const UmbrellaOff: FC<SVGProps<SVGSVGElement>>
  export const Underline: FC<SVGProps<SVGSVGElement>>
  export const Undo: FC<SVGProps<SVGSVGElement>>
  export const Undo2: FC<SVGProps<SVGSVGElement>>
  export const UndoDot: FC<SVGProps<SVGSVGElement>>
  export const UnfoldHorizontal: FC<SVGProps<SVGSVGElement>>
  export const UnfoldVertical: FC<SVGProps<SVGSVGElement>>
  export const Ungroup: FC<SVGProps<SVGSVGElement>>
  export const University: FC<SVGProps<SVGSVGElement>>
  export const Unlink: FC<SVGProps<SVGSVGElement>>
  export const Unlink2: FC<SVGProps<SVGSVGElement>>
  export const Unlock: FC<SVGProps<SVGSVGElement>>
  export const UnlockKeyhole: FC<SVGProps<SVGSVGElement>>
  export const Unplug: FC<SVGProps<SVGSVGElement>>
  export const Upload: FC<SVGProps<SVGSVGElement>>
  export const UploadCloud: FC<SVGProps<SVGSVGElement>>
  export const Usb: FC<SVGProps<SVGSVGElement>>
  export const UserCheck: FC<SVGProps<SVGSVGElement>>
  export const UserCog: FC<SVGProps<SVGSVGElement>>
  export const UserMinus: FC<SVGProps<SVGSVGElement>>
  export const UserPen: FC<SVGProps<SVGSVGElement>>
  export const UserPlus: FC<SVGProps<SVGSVGElement>>
  export const UserRound: FC<SVGProps<SVGSVGElement>>
  export const UserRoundCheck: FC<SVGProps<SVGSVGElement>>
  export const UserRoundCog: FC<SVGProps<SVGSVGElement>>
  export const UserRoundMinus: FC<SVGProps<SVGSVGElement>>
  export const UserRoundPen: FC<SVGProps<SVGSVGElement>>
  export const UserRoundPlus: FC<SVGProps<SVGSVGElement>>
  export const UserRoundSearch: FC<SVGProps<SVGSVGElement>>
  export const UserRoundX: FC<SVGProps<SVGSVGElement>>
  export const UserSearch: FC<SVGProps<SVGSVGElement>>
  export const UserX: FC<SVGProps<SVGSVGElement>>
  export const UsersRound: FC<SVGProps<SVGSVGElement>>
  export const Utensils: FC<SVGProps<SVGSVGElement>>
  export const UtensilsCrossed: FC<SVGProps<SVGSVGElement>>
  export const Variable: FC<SVGProps<SVGSVGElement>>
  export const Vault: FC<SVGProps<SVGSVGElement>>
  export const Vegan: FC<SVGProps<SVGSVGElement>>
  export const VenetianMask: FC<SVGProps<SVGSVGElement>>
  export const Vibrate: FC<SVGProps<SVGSVGElement>>
  export const VibrateOff: FC<SVGProps<SVGSVGElement>>
  export const Video: FC<SVGProps<SVGSVGElement>>
  export const VideoOff: FC<SVGProps<SVGSVGElement>>
  export const Videotape: FC<SVGProps<SVGSVGElement>>
  export const View: FC<SVGProps<SVGSVGElement>>
  export const Voicemail: FC<SVGProps<SVGSVGElement>>
  export const Volume1: FC<SVGProps<SVGSVGElement>>
  export const Volume2: FC<SVGProps<SVGSVGElement>>
  export const VolumeX: FC<SVGProps<SVGSVGElement>>
  export const Vote: FC<SVGProps<SVGSVGElement>>
  export const Wallet: FC<SVGProps<SVGSVGElement>>
  export const Wallet2: FC<SVGProps<SVGSVGElement>>
  export const WalletCards: FC<SVGProps<SVGSVGElement>>
  export const Wallpaper: FC<SVGProps<SVGSVGElement>>
  export const Wand: FC<SVGProps<SVGSVGElement>>
  export const Wand2: FC<SVGProps<SVGSVGElement>>
  export const Warehouse: FC<SVGProps<SVGSVGElement>>
  export const WashingMachine: FC<SVGProps<SVGSVGElement>>
  export const Watch: FC<SVGProps<SVGSVGElement>>
  export const Waves: FC<SVGProps<SVGSVGElement>>
  export const Waypoints: FC<SVGProps<SVGSVGElement>>
  export const Webcam: FC<SVGProps<SVGSVGElement>>
  export const Webhook: FC<SVGProps<SVGSVGElement>>
  export const Weight: FC<SVGProps<SVGSVGElement>>
  export const Wheat: FC<SVGProps<SVGSVGElement>>
  export const WheatOff: FC<SVGProps<SVGSVGElement>>
  export const WholeWord: FC<SVGProps<SVGSVGElement>>
  export const Wifi: FC<SVGProps<SVGSVGElement>>
  export const WifiOff: FC<SVGProps<SVGSVGElement>>
  export const Wind: FC<SVGProps<SVGSVGElement>>
  export const Wine: FC<SVGProps<SVGSVGElement>>
  export const WineOff: FC<SVGProps<SVGSVGElement>>
  export const Workflow: FC<SVGProps<SVGSVGElement>>
  export const Worm: FC<SVGProps<SVGSVGElement>>
  export const WrapText: FC<SVGProps<SVGSVGElement>>
  export const Wrench: FC<SVGProps<SVGSVGElement>>
  export const X: FC<SVGProps<SVGSVGElement>>
  export const XCircle: FC<SVGProps<SVGSVGElement>>
  export const XOctagon: FC<SVGProps<SVGSVGElement>>
  export const XSquare: FC<SVGProps<SVGSVGElement>>
  export const Youtube: FC<SVGProps<SVGSVGElement>>
  export const ZapOff: FC<SVGProps<SVGSVGElement>>
  export const ZoomIn: FC<SVGProps<SVGSVGElement>>
  export const ZoomOut: FC<SVGProps<SVGSVGElement>>
}
